-- ===========================================================================
-- Seed: centros de acopio importados de centrosdeacopiovzla.com (data.json)
-- Actualizado en la fuente: 2026-06-25
-- 475 centros con coordenadas (se omitieron 22 sin coords).
-- Se excluyeron 11 centros ya registrados (duplicados confirmados).
-- is_approved=false: entran a la cola de revisión para que el equipo verifique
-- duplicados y la confiabilidad de cada organización antes de publicarlos.
-- ===========================================================================

INSERT INTO "public"."centers"
  ("name","address","lat","lng","phone","schedule","whatsapp","instagram","website","email","organization","status","is_approved","is_verified")
SELECT v."name",v."address",v."lat",v."lng",v."phone",COALESCE(v."schedule",''),v."whatsapp",v."instagram",v."website",v."email",'','receiving'::"public"."center_status",false,false
FROM (VALUES
  ('CC Forum Plaza - Lechería', 'Centro Comercial Forum Plaza, Lechería, Anzoátegui', 10.188, -64.68, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Plaza de Puerto Príncipe (ubicación por confirmar)', 'Plaza de Puerto Príncipe, Anzoátegui, Anzoátegui', 10.13, -64.69, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Sociedad civil', 'Playa Mansa, Anzoátegui', 10.187, -64.696, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Gobernación del Estado Anzoátegui — Anzoátegui Solidario', 'Sede de la Gobernación del Estado Anzoátegui, Av. 5 de Julio, Barcelona, Anzoátegui', 10.134, -64.685, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Protección Civil — Barcelona', 'Sede de Protección Civil, Av. Fuerzas Armadas, Barcelona, Anzoátegui, Anzoátegui', 10.133, -64.689, NULL, NULL, NULL, NULL, NULL, NULL),
  ('ugma sede principal Barcelona', 'Avenida intercomunal, Anzoátegui', 10.1664, -64.6834, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Protección Civil — Puerto La Cruz', 'Sede de Protección Civil, Paseo de la Cruz y el Mar, Puerto La Cruz, Anzoátegui, Anzoátegui', 10.22, -64.63, NULL, NULL, NULL, NULL, NULL, NULL),
  ('El Elevado — Puerto La Cruz', 'El Elevado, Puerto La Cruz, Anzoátegui, Anzoátegui', 10.223, -64.628, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Polideportivo La Caraqueña', 'Polideportivo La Caraqueña, Puerto La Cruz, Anzoátegui, Anzoátegui', 10.216, -64.644, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Hotel Paradise Puerto la Cruz', 'Paseo Colón, Puerto La Cruz, Anzoátegui', 10.2278, -64.6329, NULL, NULL, NULL, 'paradiseplc', NULL, NULL),
  ('Club Camarón', 'Calle La Romana frente al Liceo Josefina Crespo, Cagua, Aragua', 10.17092876, -67.44659363, NULL, NULL, '4143456992', NULL, NULL, NULL),
  ('Hyper Jumbo — Maracay', 'Hyper Jumbo, Maracay, Aragua', 10.253, -67.601, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Colegio San José — Maristas', 'Aula de Dibujo II (Media General), Colegio San José, Maracay · Horario: a partir del viernes 26 de junio de 2026, de 9:00 a.m. a 12:00 p.m., Aragua', 10.247, -67.595, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Comando Con Venezuela', 'Avenida 19 de Abril, Centro Comercial La Capilla, Piso 1, Local 21, Aragua', 10.2469, -67.5958, NULL, NULL, NULL, 'https://www.instagram.com/p/DZ_kBlyIVRI/?hl=es', NULL, NULL),
  ('Redoma Gran Mariscal', 'Corinsa, Aragua', 10.17102388, -67.45307849, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Sociedad anticancerosa', 'Calle Bolívar frente a la Plaza Sucre, Aragua', 10.17451394, -67.43814467, NULL, NULL, '4143456992', NULL, NULL, NULL),
  ('Teatro de la Ópera (Maracay)', 'Teatro de la Ópera, Maracay, Aragua', 10.248, -67.595, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Burger Latin — CC Palma Center', 'Burger Latin, Centro Comercial Palma Center, La Victoria, Aragua', 10.2272, -67.332, NULL, NULL, NULL, 'https://www.instagram.com/p/DaAk8GWOLGH/?igsh=MXB2NDFyNzlheG54Nw%3D%3D', NULL, NULL),
  ('Bodega 33 — CC El Solidario', 'Bodega 33, Centro Comercial El Solidario, La Victoria, Aragua', 10.228, -67.33, NULL, NULL, NULL, NULL, NULL, NULL),
  ('CEI María de las Mercedes', 'Calle Dr. Vicentelli c/c Rosa María Paredes #7, Sector Centro, La Victoria, Aragua', 10.227, -67.334, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Parroquia Nuestra Señora del Carmen', 'Calle Colón, La Victoria, Aragua', 10.229, -67.332, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Iglesia Jesús de la Misericordia', 'Turmero, Aragua', 10.21479566, -67.48666085, NULL, NULL, '4260635514', NULL, NULL, NULL),
  ('U.E. Coronel Juan José Rondón', 'Av. Intercomunal Turmero-Maracay, frente al Mercado Mayorista (Instalaciones JJR) · Horario: a partir de las 7:30 a.m., Aragua', 10.227, -67.541, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Restaurant O''Maria', 'Carrera 5 con calles 18 y 19, Municipio Ezequiel Zamora, Santa Bárbara de Barinas, Barinas', 8.6213, -70.2051, NULL, NULL, '+584247141072', NULL, NULL, NULL),
  ('Droguería Merecure — La Floresta', 'Droguería Merecure (Local 5), CC Central Plaza, Av. 23 de Enero, La Floresta, Barinas, Barinas', 8.632, -70.208, NULL, NULL, NULL, 'drogueriamerecure', NULL, NULL),
  ('Farmacia Santa Rosa — Alto Barinas', 'Calle Justicia con Av. Venezuela, Urb. Alto Barinas Norte (frente a la Clínica Varyna), Barinas, Barinas', 8.624, -70.22, NULL, NULL, NULL, 'farmaciasantarosa_oficial', NULL, NULL),
  ('Galletera Italia — Sede Central La Industrial', 'Galletera Italia, Zona Industrial Cazdeba, Av. 02 Sur, La Industrial, Barinas, Barinas', 8.616, -70.205, NULL, NULL, NULL, 'galletera.italia', NULL, NULL),
  ('Inversiones Decolux', 'Inversiones Decolux, Caja de Agua, callejón 2, Barinas, Barinas', 8.623, -70.212, NULL, NULL, NULL, 'decolux', NULL, NULL),
  ('Delgadillo FerreAgro', 'Av. Coddazi, diagonal al parque Jimmy Flores, Barinas · Horario: 7:30 a.m. a 6:00 p.m., Barinas', 8.621, -70.216, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Celsas Bocaditos', 'Calle Mérida, entre Av. Olímpica y San Martín, frente a Licocenter, Barinas, Barinas', 8.626, -70.211, NULL, NULL, NULL, 'celsasbocaditos', NULL, NULL),
  ('Comando Con Venezuela', 'Av. Marqués del Pumar diagonal al Hotel Comercio, Casa Azul, Barinas', 8.6231, -70.2075, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Fe y Alegría "Padre Felipe Salvador Gilij"', 'Fe y Alegría Padre Felipe Salvador Gilij, Barinas, Barinas', 8.6050614, -70.1956269, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Comando Con Venezuela', 'Municipio Cruz Paredes, Av. Bolívar diagonal al Hotel del Búfalo, Casa Azul, Barrancas, Barinas', 8.623314, -70.210987, NULL, NULL, '4145298154', NULL, NULL, NULL),
  ('Comando Con Venezuela', 'Municipio Caroní: Centro Comercial Biblos, primer piso, Local 71 C (antes Todo Limpio, frente a los tráileres de Bauxilum y al lado de la Bomba Biblos), Unare II, Bolívar', 8.120393, -63.547336, NULL, NULL, NULL, 'https://www.instagram.com/p/DZ_0rjlljwk/?igsh=MWJwbTk1MXhhYWtkcg%3D%3D', NULL, NULL),
  ('Cámara de Comercio de Bolívar', 'Sede de la Cámara de Comercio e Industrias del estado Bolívar, Av. Táchira, Bolívar', 8.1222, -63.5497, NULL, NULL, NULL, 'camaradecomerciobolivar', NULL, NULL),
  ('Gobierno de Venezuela', 'Fundación Social Bolívar (Sede 911), Bolívar', 8.297, -62.717, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Rotaract Santo Ángel', 'Croquínea a un lado de la Clínica Razzeti, Altavista, Bolívar', 8.353, -62.651, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Voluntad Popular - Angostura del Orinoco', 'Esquina de Banesco, Avenida República, Municipio Angostura del Orinoco (Ciudad Bolívar), Bolívar', 8.128, -63.543, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Comando Con Venezuela', 'Municipio Heres: Av. Pichincha, Edificio Tequendama, Local N° 4, Bolívar', 8.122414, -63.553187, NULL, NULL, NULL, 'https://www.instagram.com/p/DZ_0rjlljwk/?igsh=MWJwbTk1MXhhYWtkcg%3D%3D', NULL, NULL),
  ('UCAB Guayana - Casa del Estudiante', 'Planta alta, Casa del Estudiante, Dirección de Desarrollo Estudiantil, UCAB Guayana, Puerto Ordaz, Bolívar', 8.2965, -62.7185, NULL, NULL, '4249147305', NULL, NULL, NULL),
  ('Rotaract Santo Ángel', 'Laboratorio Roraima, Clínica Humana San Félix, Bolívar', 8.351193, -62.648636, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Iglesia La Esmeralda', 'Iglesia La Esmeralda, San Diego, Carabobo', 10.24, -67.97, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Iglesia Pueblo de San Diego', 'Iglesia Pueblo de San Diego, San Diego, Carabobo', 10.242, -67.972, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Cuerpo de Bomberos de Guacara', 'Sede del Cuerpo de Bomberos, Carretera Nacional, Guacara, Carabobo', 10.231, -67.877, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Cuerpo de Bomberos Universidad de Carabobo', 'Sede del Cuerpo de Bomberos, Universidad de Carabobo, Valencia, Carabobo', 10.164, -68.008, NULL, NULL, NULL, NULL, NULL, NULL),
  ('G3 Logística — Valencia', 'Calle La Pedrera, Fundo Los Marines, Zona Industrial San Diego, Carabobo', 10.243, -68.001, NULL, 'Lunes a viernes, 9:00am - 12:00pm y 2:00pm - 3:30pm', NULL, NULL, NULL, NULL),
  ('Asociación de Ejecutivos del estado Carabobo (AEEC)', 'Av. 119 Teodoro Gubaira, Edif. 122-145, Urbanización Valle de Camoruco (4ta Avenida de Prebo), Valencia, Carabobo', 10.173, -68.009, NULL, 'Lunes a viernes, 9:00am - 4:00pm', NULL, 'aeecoficial', NULL, NULL),
  ('Grupo Nezco Venezuela — Valencia', 'Calle Lisandro Ramírez #97-30, Parroquia San Blas, Valencia, Carabobo', 10.166, -68.003, NULL, NULL, '+584246491600', NULL, NULL, NULL),
  ('Casa Amira — Amira Studio & Mosaico', 'Casa Amira, Calle Alejo Zuluaga, Av. Z, El Trigal Norte, Valencia, Carabobo', 10.17, -68.015, NULL, 'Viernes 26 de junio, 10:00am - 3:00pm', NULL, '_amirastudio', NULL, NULL),
  ('Comando Con Venezuela', 'Avenida Monseñor Adams, El Viñedo. Edificio Talislandia, mezzanina., Carabobo', 10.160193, -68.005336, NULL, NULL, NULL, 'https://www.instagram.com/p/DZ_kBlyIVRI/?hl=es', NULL, NULL),
  ('Jóvenes por el clima', 'Av. Bolívar frente al Multicentro, Carabobo', 10.162, -68.0077, NULL, NULL, NULL, 'https://www.instagram.com/p/DaAB8S-CAiB/?igsh=Njl4YXk4N3drM2tm', NULL, NULL),
  ('Plaza de las Panelas', 'Indiana Norte, Carabobo', 10.25665613, -67.80182411, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Ballroom Valencia / Fundación MAVID', 'Urb. Tarapío, Calle 189 c/c Av. 104, Naguanagua (a 2 cuadras del semáforo de la 190) · Horario: L-V 8:30am-4pm, Sáb 9am-1pm, Carabobo', 10.253, -68.012, NULL, NULL, NULL, 'ballroom.vzla', NULL, NULL),
  ('CONNECTION ACADEMY', 'SECTOR LA CANDELARIA CENTRO COMERCIAL BAHIA IMPERIAL, Carabobo', 10.1774, -68.0068, NULL, NULL, NULL, 'connectionacademy_ve', NULL, NULL),
  ('Plaza de flor amarillo.', 'Plaza de flor amarillo, c, Carabobo', 10.1381, -67.9449, '04247608331', NULL, NULL, NULL, NULL, NULL),
  ('Escuela Manaure', 'Escuela Manaure, Cojedes', 9.823081108, -68.43389031, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Cáritas San Carlos', 'Sede Cáritas Diocesana, calle Carabobo con calle Madariaga, San Carlos, Cojedes', 9.664781388, -68.58874388, NULL, NULL, NULL, 'caritasdiocesanasancarlos', NULL, NULL),
  ('Cáritas Venezuela', 'Sede de la Conferencia Episcopal Venezolana, Avenida Teherán, a 200 metros de la Universidad Católica Andrés Bello (UCAB), frente a la Urbanización Juan Pablo II, sector Montalbán, Distrito Capital', 10.461193, -66.939636, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Caracas FC — Cocodrilos Sports Park', 'Cocodrilos Sports Park, Av. Antonio Guzmán Blanco, entre el Parque El Pinar y La India, El Paraíso, Caracas · Sede administrativa y de entrenamiento del Caracas Fútbol Club · Horario: desde el sábado 27 de junio, 8:00 a.m. a 6:00 p.m., Distrito Capital', 10.481, -66.932, NULL, NULL, NULL, 'caracas_fc', NULL, NULL),
  ('Centro de Acopio UCV — Gestión Menstrual (Plaza del Rectorado)', 'Plaza del Rectorado, Universidad Central de Venezuela (UCV), Caracas · Para mujeres, niñas y adolescentes de La Guaira y El Junquito, Distrito Capital', 10.491, -66.891, '+584143356422', NULL, NULL, 'marialaurarg', NULL, NULL),
  ('FCU-UCV — Plaza Rectorado', 'Plaza Rectorado, Universidad Central de Venezuela (UCV), Caracas, Distrito Capital', 10.49, -66.89, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Alcaldía de Chacao — Sede de Desarrollo Social', 'Sede de Desarrollo Social, Calle Los Ángeles, lateral al CC Sambil Chacao, Municipio Chacao, Distrito Capital', 10.496, -66.854, '+584241285989', NULL, NULL, 'alcaldiachacao', NULL, NULL),
  ('Edificio Rita Palace — Los Caobos', 'Edif. Rita Palace, Av. La Salle, Planta Baja, Los Caobos, Distrito Capital', 10.501, -66.913, NULL, NULL, '+584145634459', NULL, NULL, NULL),
  ('Colegio Cristo Rey Altamira', 'Colegio Cristo Rey Altamira, 7ma Avenida entre 6ta y 7ma Transversal, Distrito Capital', 10.496491, -66.844222, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Comando Con Venezuela', 'Cuarta Avenida de Altamira, entre novena y décima transversal, Quinta El Bejucal, Distrito Capital', 10.493193, -66.844636, NULL, NULL, NULL, 'https://www.instagram.com/p/DZ_kBlyIVRI/?hl=es', NULL, NULL),
  ('Fundación Cruz Azul', 'Fitness Factory VE, 4ta Avenida de Los Palos Grandes entre 1ra y 2da transversal, Distrito Capital', 10.496193, -66.839636, NULL, NULL, NULL, 'cruzazulusm', NULL, NULL),
  ('Iglesia La Paz Montalbán I', 'Iglesia La Paz Montalbán I, Distrito Capital', 10.47599064, -66.95098002, NULL, NULL, NULL, 'comandoconvzla', NULL, NULL),
  ('Instituto de Diseño de Caracas', 'Av. Ávila, Caracas 1060, Miranda, Distrito Capital', 10.4806, -66.9036, NULL, NULL, '4123212782', NULL, NULL, NULL),
  ('Rescatistas y Vecinos — Altamira CAF', 'Altamira, frente a la sede de la CAF, Caracas, Distrito Capital', 10.495, -66.847, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Rescatistas y vecinos — Edificio Petunia', 'Edificio Petunia, Av. Francisco de Miranda entre Los Palos Grandes y Altamira, Caracas, Distrito Capital', 10.498, -66.842, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Rotaract Caracas - Terrazas del Club Hípico', 'Terrazas del Club Hípico, Caracas, Distrito Capital', 10.452, -66.843, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Sede de la Conferencia Episcopal de Venezuela', 'Avenida Teherán, Urbanización Montalbán / Juan Pablo II., Distrito Capital', 10.47020196, -66.96065049, NULL, NULL, NULL, 'cevmedios', NULL, NULL),
  ('Toneladas de Alegría', 'Edificio VVZ, Av. Sorocaima, Caracas, Distrito Capital', 10.492, -66.858, NULL, NULL, NULL, 'toneladasdealegria', NULL, NULL),
  ('Sociedad civil', 'Quinta El Bejucal, cuarta Avenida transversal de Altamira, entre novena y décima transversal, Distrito Capital', 10.495214, -66.850487, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Iglesia Santo Domingo Savio', 'A una cuadra de la estación de policia, Distrito Capital', 10.445, -66.9276, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Colegio Nacional de Periodistas (CNP) - Paraguaná', 'Sede del Colegio Nacional de Periodistas (CNP), Paraguaná, Falcón', 11.69, -70.21, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Alcaldía de Carirubana — Plazoleta del Mercado Turístico', 'Plazoleta del Mercado Turístico, Av. Principal Antiguo Aeropuerto, Parroquia Norte, Punto Fijo (Municipio Carirubana) · Horario: 8:00 a.m. a 8:00 p.m., Falcón', 11.7045, -70.215, '+584126617682', NULL, NULL, 'alcariubana', NULL, NULL),
  ('Total Motos Falcón', 'Calle Peninsular, esquina Las Palmas, Local 2, diagonal a Imaseo, Punto Fijo · Horario: a partir de la 1:00 p.m., Falcón', 11.708, -70.21, '+584126663055', NULL, NULL, 'punto_fijo_novedades', NULL, NULL),
  ('GoldStars Gym — Sede Sambil', 'GoldStars Gym, Sambil Paraguaná, Punto Fijo, Falcón', 11.7068, -70.2086, NULL, NULL, NULL, NULL, NULL, NULL),
  ('GoldStars Gym — Sede CC Las Virtudes', 'GoldStars Gym, Centro Comercial Las Virtudes, Punto Fijo, Falcón', 11.685, -70.2106, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Alas Viajeras', 'Oficina Alas Viajeras, Hotel Puerto Plata, Punto Fijo, Falcón', 11.696, -70.2153, NULL, NULL, '+584146522514', NULL, NULL, NULL),
  ('Cáritas Diócesis de Punto Fijo', 'Sector Centro, calle Páez entre Brasil y Perú, frente a la primera casa de Punto Fijo, Falcón', 11.708, -70.199, NULL, 'Lunes a viernes, 8:30am - 2:00pm', NULL, NULL, NULL, NULL),
  ('RE/MAX Avanti', 'C.C.R ''Las Virtudes'' Local F1-5, Falcón', 11.6585, -70.2048, '+584146967465', NULL, NULL, 'avantiremax.ve', NULL, NULL),
  ('Tambú Sushi', 'C.C.R ''Las Virtudes'' Nivel galería, Falcón', 11.658, -70.2056, '+584220291641', NULL, NULL, 'tambusushivzla', NULL, NULL),
  ('Gobernación del Estado Bolivariano de Guárico — Centro Principal', 'Gobernación del Estado Bolivariano de Guárico, San Juan de los Morros, Guárico · Horario: lunes a domingo, 8:00 a.m. a 6:00 p.m., Guárico', 9.909, -67.354, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Parque Antonio Miguel Martínez', 'Parque Antonio Miguel Martínez, San Juan de los Morros, Guárico, Guárico', 9.909, -67.355, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Paseo Doña Lola', 'CC Paseo Doña Lola, Calle Páez cruce Av. Sendrea con Av. Bolívar, al lado del restaurante The One Place, San Juan de los Morros · Horario: 7:00 a.m. a 8:00 p.m., Guárico', 9.909, -67.354, NULL, NULL, NULL, 'Paseo_dona_lola', NULL, NULL),
  ('Plaza Bolívar — Ortiz', 'Plaza Bolívar, Ortiz, Guárico, Guárico', 9.619, -67.3, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Desarrollo Social de la Alcaldía', 'Desarrollo Social de la Alcaldía, calle Vigía, Valle de la Pascua, Guárico, Guárico', 9.215, -65.997, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Salón de Usos Múltiples de la Alcaldía — Guayabal', 'Salón de Usos Múltiples de la Alcaldía, Guayabal, Guárico, Guárico', 8.58, -67.4, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Concejo Municipal — Santa María', 'Concejo Municipal, Santa María de Ipire, Guárico, Guárico', 8.961, -65.326, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Alcaldía de El Sombrero', 'Alcaldía de El Sombrero, Guárico, Guárico', 9.385, -67.05, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Salón de Usos Múltiples de la Alcaldía — Calabozo', 'Salón de Usos Múltiples de la Alcaldía, Calabozo, Guárico, Guárico', 8.924, -67.426, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Plaza Castor Vásquez y Plaza Bolívar de Puerto Miranda', 'Plaza Castor Vásquez y Plaza Bolívar de Puerto Miranda, Camaguán, Guárico, Guárico', 8.119, -67.598, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Instituto de Deportes IMDRI', 'Instituto de Deportes IMDRI, Tucupido, Guárico, Guárico', 9.298, -65.771, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Alcaldía de Altagracia de Orituco', 'Alcaldía de Altagracia de Orituco, Guárico, Guárico', 9.877, -66.383, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Casa de la Cultura — Las Mercedes del Llano', 'Casa de la Cultura, Las Mercedes del Llano, Guárico, Guárico', 9.11, -66.4, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Cuerpo de Bomberos — Zaraza', 'Cuerpo de Bomberos, Zaraza, Guárico, Guárico', 9.352, -65.321, NULL, NULL, NULL, NULL, NULL, NULL),
  ('PAC de la GNB — Chaguaramas', 'Puesto de Atención al Ciudadano (PAC) de la Guardia Nacional Bolivariana, Chaguaramas, Guárico, Guárico', 9.336, -66.253, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Sala Situacional de Seguridad y Paz', 'Sala Situacional de Seguridad y Paz, Plaza Bolívar, Sector Centro, Guaribe, Guárico, Guárico', 9.829, -65.595, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Comandancia del Sector Calichito', 'Comandancia del Sector Calichito, calle Bolívar, El Socorro, Guárico, Guárico', 8.992, -65.722, NULL, NULL, NULL, NULL, NULL, NULL),
  ('G3 Logística — Barquisimeto', 'Zona Industrial II, Av. Principal con Calle 6, locales 110-111-112, Lara', 10.069, -69.314, NULL, 'Lunes a viernes, 9:00am - 12:00pm y 2:00pm - 3:30pm', NULL, NULL, NULL, NULL),
  ('Grupo Nezco Venezuela — Barquisimeto', 'Carrera 18 con Calle 49, al lado de SEIPCA, Puerta Negra, Barquisimeto, Lara', 10.07, -69.322, NULL, NULL, '+584126938188', NULL, NULL, NULL),
  ('Operación Todos con VZLA — Iribarren', 'Av. Venezuela al lado del Sambil, canal lento desde la Av. Morán hasta el Sambil, al lado de Seguros Altamira, Barquisimeto, Lara', 10.064, -69.32, NULL, NULL, NULL, 'convzlacomando', NULL, NULL),
  ('Cáritas Barquisimeto', 'Cáritas, Carrera 18 entre calles 34 y 35, Barquisimeto, Lara', 10.068, -69.323, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Colegio Las Colinas', 'Colegio Las Colinas, entrada El Pedregal, Lara', 10.064914, -69.350487, NULL, NULL, NULL, 'colegiolascolinas1969', NULL, NULL),
  ('Fitness Factory Cabudare', 'CC Hipermercado Multimall, Avenida El Placer con Av. Libertador, Lara', 10.0286, -69.2611, NULL, NULL, NULL, 'https://www.instagram.com/p/DaApx5TAAkN/?img_index=1&igsh=MWprOWNwODh2eHowdA==', NULL, NULL),
  ('Sociedad civil', 'Tatas Food, carrera 15 entre calles 13A y 13B, Lara', 10.0647, -69.347, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Voluntariado Higea', 'Fundación Higea y Biotel Suites, Lara', 10.062893, -69.344636, NULL, NULL, NULL, 'voluntariadohigea', NULL, NULL),
  ('FUNDACIÓN TEJIENDO REDES', 'CALLE 41 ENTRE CARRERAS 13 Y 14 CASA 13-50, Lara', 10.0595, -69.3323, NULL, NULL, NULL, 'https://www.instagram.com/fundaciontejiendoredes?igsh=MTlqamVjMnBvMjB4cw==', NULL, NULL),
  ('ESTADIO DE SOFTBOL Aquiles Machado', 'Calle 64 con carrera 13, detrás de las piscinas Bolivarianas, Lara', 10.05, -69.3545, '4120179138', NULL, NULL, NULL, NULL, NULL),
  ('Operación Todos con VZLA — Palavecino', 'Los Rastrojos, Calle 3, esquina Calle Aquilino Juárez, diagonal Centro Deportivo El Cuadrito, detrás de la Escuela Pedro Gual, Lara', 10.015, -69.23, NULL, NULL, NULL, 'convzlacomando', NULL, NULL),
  ('Operación Todos con VZLA — Jiménez', 'Avenida 5 entre Calle 13 y 14, Parroquia Juan Bautista Rodríguez, Quíbor, Lara', 9.929, -69.632, NULL, NULL, NULL, 'convzlacomando', NULL, NULL),
  ('Operación Todos con VZLA — Crespo', 'Calle 13 entre Carreras 12 y 13, Duaca, Lara', 10.27, -69.139, NULL, NULL, NULL, 'convzlacomando', NULL, NULL),
  ('Operación Todos con VZLA — Torres', 'Academia Cecilio Acosta, Av. Dr. Pastor Oropeza entre calles 6 y 7, Sector Antonio José de Sucre, una cuadra antes de Monpet, Carora, Lara', 10.175, -70.079, NULL, NULL, NULL, 'convzlacomando', NULL, NULL),
  ('El Sistema — Núcleo Mérida', 'El Sistema Nacional de Orquestas y Coros Juveniles e Infantiles, Núcleo Mérida, Calle 37 entre Av. 2 y 3, Sector Glorias Patrias, Mérida · Horario: sábado 27 de junio, 9:00 a.m. a 4:00 p.m., Mérida', 8.591, -71.15, NULL, NULL, NULL, 'programa.musicapopularmerida', NULL, NULL),
  ('Local Scuderia — Mérida se une', 'Local Scuderia, final Av. 16 de Septiembre con calle Miranda, diagonal a las canchas del Luis Ghersi, Mérida, Mérida', 8.583, -71.149, '+584247659598', NULL, NULL, NULL, NULL, NULL),
  ('Traki Mérida', 'Edificio Traki, Av. Los Próceres, Mérida · Horario: 8:30 a.m. a 8:00 p.m., Mérida', 8.587, -71.162, NULL, NULL, NULL, 'meridaven', NULL, NULL),
  ('Universidad de Los Andes (ULA) — Edificio del Rectorado', 'Edificio del Rectorado, Universidad de Los Andes, Mérida · Horario: viernes 26/6/26, 8:30 a.m. a 2:00 p.m., Mérida', 8.587, -71.145, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Animales Sin Nombre', 'Centro Comercial El Rodeo, Av. Las Américas, frente a la Estación de Servicio Alba Lago, Mérida 5101 · Contactar también por Instagram, Mérida', 8.5899, -71.1611, NULL, NULL, NULL, '_asn', NULL, NULL),
  ('Colegio de Médicos de Mérida', 'Sede del Colegio de Médicos de Mérida, Mérida', 8.5916, -71.1448, NULL, NULL, NULL, NULL, NULL, NULL),
  ('CC Rodeo Plaza — Piso 1', 'CC Rodeo Plaza, Av. Andrés Bello, Mérida, Mérida', 8.581, -71.148, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Servisalud / Farmacia Micori', 'Servisalud / Farmacia Micori, Mérida, Mérida', 8.587, -71.145, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Fuerza ULA — Patio Central de FACIJUP', 'Patio Central de FACIJUP, Universidad de Los Andes, Mérida, Mérida', 8.59, -71.145, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Edificio Administrativo de la ULA', 'Edificio Administrativo, Universidad de Los Andes, Mérida, Mérida', 8.591, -71.148, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Escuela Vicente Dávila — Parroquia Milla', 'Escuela Vicente Dávila, Parroquia Milla, Mérida, Mérida', 8.602, -71.143, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Liceo Ezequiel Zamora — Parroquia Arias', 'Liceo Ezequiel Zamora, Parroquia Arias, Mérida, Mérida', 8.585, -71.153, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Escuela El Educador — Parroquia Jacinto Plaza', 'Escuela El Educador, Parroquia Jacinto Plaza, Mérida, Mérida', 8.599, -71.139, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Politécnico Santiago Mariño — Mérida', 'Politécnico Santiago Mariño, Mérida, Mérida', 8.584, -71.141, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Facultad de Medicina ULA', 'Facultad de Medicina, Universidad de Los Andes, Mérida, Mérida', 8.5915, -71.147, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Facultad de Ingeniería ULA', 'Facultad de Ingeniería, Universidad de Los Andes, Mérida, Mérida', 8.5905, -71.149, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Hiper Garzón — Las Américas', 'Hiper Garzón, Av. Las Américas, Mérida, Mérida', 8.575, -71.167, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Cumis Por Venezuela', 'Cumis Por Venezuela, Mérida, Mérida', 8.588, -71.144, NULL, NULL, NULL, NULL, NULL, NULL),
  ('McDonald''s Av. Las Américas', 'McDonald''s, Av. Las Américas, Mérida, Mérida', 8.577, -71.164, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Plaza de la Parroquia', 'Plaza de la Parroquia, Mérida, Mérida', 8.59, -71.143, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Farmacia Las Tapias', 'Farmacia Las Tapias, Av. Andrés Bello, Mérida, Mérida', 8.567, -71.157, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Estudiantes de Comunicación Social — ULA', 'Escuela de Comunicación Social, Universidad de Los Andes, Mérida, Mérida', 8.591, -71.148, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Liceo Libertador — Parroquia El Llano', 'Liceo Libertador, Parroquia El Llano, Mérida, Mérida', 8.597, -71.141, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Comisión de Bomberos ULA', 'Comisión de Bomberos ULA, Universidad de Los Andes, Mérida, Mérida', 8.591, -71.148, NULL, NULL, NULL, NULL, NULL, NULL),
  ('REFULA — Av. Don Tulio', 'REFULA (Residencia Estudiantil), Av. Don Tulio, Mérida, Mérida', 8.5905, -71.147, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Av. Universidad — Mérida', 'Av. Universidad, Mérida, Mérida', 8.584, -71.15, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Plaza Las Heroínas', 'Plaza Las Heroínas, Mérida (al lado del Teleférico), Mérida', 8.581, -71.145, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Mérida Grill — CC Rodeo', 'Mérida Grill, CC Rodeo Plaza, Av. Andrés Bello, Mérida, Mérida', 8.581, -71.148, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Sede Protección Civil — Mérida', 'Sede de Protección Civil del Estado Mérida, Mérida, Mérida', 8.5905, -71.146, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Tealca — Av. Universidad', 'Tealca, Av. Universidad, Mérida, Mérida', 8.584, -71.15, NULL, NULL, NULL, NULL, NULL, NULL),
  ('FitnessWorld — Mérida', 'FitnessWorld, Mérida, Mérida', 8.586, -71.148, NULL, NULL, NULL, NULL, NULL, NULL),
  ('UNEARTE — Mérida', 'UNEARTE, Mérida, Mérida', 8.59, -71.145, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Cáritas Mérida', 'Sede de Cáritas, Mérida, Mérida', 8.591, -71.146, NULL, NULL, NULL, NULL, NULL, NULL),
  ('SPOT — Mérida', 'SPOT, Mérida, Mérida', 8.586, -71.149, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Suraki — Av. Las Américas', 'Suraki, Av. Las Américas, Mérida, Mérida', 8.577, -71.164, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Farmabien — todas sus sedes', 'Farmabien (todas sus sedes), Mérida, Mérida', 8.587, -71.148, NULL, NULL, NULL, NULL, NULL, NULL),
  ('CETA — El Vigía', 'CETA, Av. 16, Sector Barrio El Carmen, El Vigía, Mérida · Horario: hasta las 6:00 p.m., Mérida', 8.624, -71.647, NULL, NULL, NULL, 'cetaenlinea', NULL, NULL),
  ('Gaman Grill', 'Gaman Grill, El Vigía, Mérida, Mérida', 8.624, -71.646, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Plaza de Ejido', 'Plaza Bolívar de Ejido, Mérida, Mérida', 8.5443, -71.231, NULL, NULL, NULL, NULL, NULL, NULL),
  ('CC Centenario', 'Centro Comercial Centenario, Ejido, Mérida, Mérida', 8.5451, -71.235, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Centro Campesino — Mucuchíes', 'Centro Campesino, Mucuchíes, Mérida, Mérida', 8.756, -70.918, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Centro de Acopio San Antonio — Bulevar de Las Minas', 'Bulevar de Las Minas, frente al Farmatodo, San Antonio de Los Altos, Miranda', 10.37, -66.945, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Complejo Cultural Los Salias', 'Complejo Cultural Los Salias, San Antonio de Los Altos, Miranda', 10.372, -66.946, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Alcaldía de Baruta — Plaza Alfredo Sadel', 'Plaza Alfredo Sadel, Las Mercedes, Municipio Baruta, Miranda', 10.4736, -66.8606, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Alcaldía de Baruta — Sede de la Policía', 'Sede de la Policía Municipal de Baruta, Municipio Baruta, Miranda', 10.435, -66.866, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Alcaldía de Baruta — Sede Protección Civil El Cafetal', 'Sede de Protección Civil El Cafetal, Municipio Baruta, Miranda', 10.45, -66.835, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Alcaldía de Baruta — Concha Acústica de Bello Monte', 'Concha Acústica, Colinas de Bello Monte, Municipio Baruta · Horario: 24 horas, Miranda', 10.483, -66.865, NULL, NULL, NULL, 'alcaldiabaruta', NULL, NULL),
  ('Woman Clinix — Los Dos Caminos', 'Sede de Woman Clinix, Av. Sucre de Los Dos Caminos, Caracas · Horario: desde las 8:00 a.m., Miranda', 10.495, -66.844, NULL, NULL, NULL, 'womanclinix', NULL, NULL),
  ('Base de Operaciones Tu Gruero — Los Dos Caminos', 'Av. El Carmen de Los Dos Caminos, diagonal a Iglesia Claret, Miranda', 10.494, -66.842, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Polideportivo Los Naranjos (Belisario Academy)', 'Polideportivo Los Naranjos, Av. Este 3, Los Naranjos, Municipio El Hatillo, Miranda', 10.443, -66.835, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Sociedad civil — Vía La Unión', 'Frente a la iglesia Rumana, en la entrada a la vía de La Unión, Miranda', 10.4233, -66.823, NULL, NULL, '+584142384085', NULL, NULL, NULL),
  ('Canchas de fútbol striker', 'El cafetal San Luis, Miranda', 10.4667, -66.8426, NULL, NULL, NULL, 'hibrido.fit', NULL, NULL),
  ('Las Tabaqueras', 'Av. Sorocaima, Urb Juan Iturbe, Edif. Las Tabaqueras, La Trinidad., Miranda', 10.433, -66.8593, NULL, NULL, NULL, 'rodandoenfamiliaporvenezuela', NULL, NULL),
  ('UNEFA SEDE PRINCIPAL', 'entre la Av. La Estancia y la Av. Caracas con calle Holanda, frente al Edificio Banaven (Cubo Negro), Miranda', 10.4831, -66.8532, NULL, NULL, NULL, 'https://www.instagram.com/riverabastardo?igsh=MTU5djY3ZzRvenFtcQ==', NULL, NULL),
  ('Tecnosegura', 'Av. Bolívar, frente al Banco de Venezuela, puerta azul al lado del Potente, arriba de Farmapaz, Maturín, Monagas, Monagas', 9.74706558, -63.18507021, NULL, NULL, NULL, NULL, NULL, NULL),
  ('UECA "Dr. Braulio Pérez Marcio"', 'Urbanización Alberto ravell, detrás del hospital universitario Manuel Núñez Tovar, Monagas', 9.7429, -63.1997, NULL, NULL, NULL, 'uecabraulioperezmarcio.oficial', NULL, NULL),
  ('Cede postgrado unesr', 'Av libertador, Monagas', 9.7313, -63.1947, '4121983945', NULL, NULL, NULL, NULL, NULL),
  ('Universidad de oriente', 'Avenida universidad, Monagas', 9.7254, -63.1902, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Iglesia Casa de Dios', 'Av. Libertador, Antiguo galpón de la Mitsubishi, detrás de Papa y son, Monagas', 9.738, -63.1658, NULL, NULL, NULL, 'Casadediossobrenatural', NULL, NULL),
  ('Centro Comercial Sambil Margarita', 'Sambil Margarita, Av. Jóvito Villalba, Sector San Lorenzo, Pampatar 6316, Nueva Esparta · Horario: 10:00 a.m. a 9:00 p.m., Nueva Esparta', 11.005, -63.79, NULL, NULL, NULL, 'tusambilmgta', NULL, NULL),
  ('Colegio de Ingenieros del Estado Portuguesa (CEINPORT)', 'Sede del Colegio de Ingenieros del Estado Portuguesa, Guanare, Portuguesa', 9.044, -69.751, '+584167561364', NULL, NULL, NULL, NULL, NULL),
  ('General Service 8a', 'Corredor vial esquina calle 7, al lado del Centro Comercial Giramara, Guanare · Horario: lunes a sábado, 8:00 a.m. a 6:00 p.m., Portuguesa', 9.044, -69.751, '+584121558915', NULL, NULL, 'generalservice8a', NULL, NULL),
  ('Centro de Acopio 5ta Transversal', '5ta transversal, Av. Gran Mariscal y Av. Santa Rosa, entre Zen y Los Hermanos Wasi, Sucre', 10.461, -64.176, NULL, '9:00am - 6:00pm', NULL, NULL, NULL, NULL),
  ('Cruz Roja Venezolana — Sucre', 'Sede de la Cruz Roja Venezolana, Municipio Sucre, Cumaná, Sucre', 10.456, -64.172, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Protección Civil Sucre — Sedes oficiales', 'Sedes de Protección Civil y Administración de Desastres, Municipio Sucre, Cumaná, Sucre', 10.4548, -64.171, NULL, NULL, NULL, NULL, NULL, NULL),
  ('UNESR — Núcleo Mariscal Antonio José de Sucre', 'Universidad Nacional Experimental Simón Rodríguez, Núcleo Mariscal Antonio José de Sucre, Cumaná, Sucre', 10.46, -64.173, NULL, '8:30am - 5:30pm', NULL, NULL, NULL, NULL),
  ('UNESR — Núcleo Mariscal Antonio José de Sucre', 'Universidad Nacional Experimental Simón Rodríguez, Núcleo Mariscal Antonio José de Sucre, Mariguitar, Sucre', 10.434, -63.917, NULL, '8:30am - 5:30pm', NULL, NULL, NULL, NULL),
  ('Universidad de Los Andes — Núcleo Táchira', 'Núcleo Táchira de la ULA, San Cristóbal, Táchira', 7.766, -72.23, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Ven Únete — Sede Civil', 'Sede de Civil, Edificio A, Cochineras, San Cristóbal, Táchira', 7.767, -72.216, NULL, 'A partir del jueves 25 de junio', NULL, NULL, NULL, NULL),
  ('Rotaract Zona Táchira — Revista Rotaria', 'Revista Rotaria, frente a la Cruz Roja, San Cristóbal, Táchira', 7.765093, -72.222636, NULL, NULL, '+584147121207', NULL, NULL, NULL),
  ('Rotaract Zona Táchira — Edificio Rotario Dr. Augusto Peña Sosa', 'Edificio Rotario Dr. Augusto Peña Sosa, Piso 2, Avenida 19 de Abril, San Cristóbal, Táchira', 7.767114, -72.228487, NULL, '8:00am - 4:00pm', NULL, NULL, NULL, NULL),
  ('MUN UCAT — Boulevard de la UCAT', 'Boulevard de la UCAT, sede vieja, Barrio Obrero, San Cristóbal, Táchira', 7.7607, -72.235, NULL, '25 y 26 de junio', NULL, NULL, NULL, NULL),
  ('Hotel Eurobuilding El Tama — Idea Market local 5', 'Hotel Eurobuilding El Tama, Idea Market, local 5, San Cristóbal, Táchira', 7.775, -72.205, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Supermarket SC', 'Centro de Acopio Supermarket SC, San Cristóbal, Táchira', 7.7669, -72.225, NULL, NULL, NULL, 'supermarket_sc', NULL, NULL),
  ('Madeco — Centro de Acopio', 'Madeco, Av. Cuatricentenaria, San Cristóbal, Táchira', 7.7669, -72.225, NULL, NULL, NULL, 'madeco_contigo', NULL, NULL),
  ('Centro de Acopio UNET — FUNDEUNET', 'Centro de Acopio UNET (Universidad Nacional Experimental del Táchira), San Cristóbal, Táchira', 7.768, -72.227, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Centro de Acopio Universitario — FCCU, Cogobierno y Alpha', 'Sede Industrial, Edificio A, al lado de Proveeduría (pasando la peluquería), San Cristóbal, Táchira', 7.768, -72.227, NULL, 'Recepción a partir del viernes 26 de junio, desde las 8:00am', NULL, 'alphauniversidad', NULL, NULL),
  ('Policlínica Táchira', 'Av. Rotaria, Táchira', 7.7587, -72.2142, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Universidades experimental del Tachira (UNET)', 'Pueblo nuevo, San Cristóbal, Táchira', 7.7923, -72.2018, NULL, NULL, NULL, 'ven.unete', NULL, NULL),
  ('Rotaract Zona Táchira — Brave Community Fitness', 'Brave Community Fitness, al lado del Hotel Manuel, San Antonio del Táchira, Táchira', 7.8146, -72.443, NULL, NULL, '+573508741816', NULL, NULL, NULL),
  ('Rotaract Zona Táchira — Centro Médico Rotario César Darío González', 'Centro Médico Rotario César Darío González, Táriba, Táchira', 7.8186, -72.2236, NULL, NULL, '+582763949051', NULL, NULL, NULL),
  ('Sociedad civil', 'Municipio Pampanito: Pampanito I, Urb. Villa Hermosa, 4ta calle, Casa N° 377, Trujillo', 9.366914, -70.436787, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Centro de Acopio Municipio Sucre', 'Urb. El Trompillo 2, parroquia Valmore Rodríguez, casa #39, Municipio Sucre, Trujillo', 9.472, -70.74, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Sociedad civil', 'Municipio Trujillo Capital. Centro Comercial Plaza Marina. Local 30, Trujillo', 9.3667, -70.4333, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Casa Prada — Sociedad Civil', 'Av. Principal La Floresta, sector Santa Elena, Casa G-11 (Casa Prada), Valera, Trujillo', 9.3187, -70.6036, NULL, NULL, NULL, NULL, NULL, NULL),
  ('RELEVECA', 'Ciudad Ojeda, Centro Comercial Reycall, frente a la E/S La Tropicana, Zulia', 10.1887, -71.3109, NULL, NULL, NULL, 'releveca_ca', NULL, NULL),
  ('Bomberos de Ciudad Ojeda', 'Plaza Bolívar de Ciudad Ojeda, Zulia · Horario: lunes a sábado, 9:00 a.m. a 6:00 p.m., Zulia', 10.1968, -71.3151, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Frutería al lado del Banco Mercantil — Centro de Acopio', 'Frutería al lado del Banco Mercantil, Lagunillas, Ciudad Ojeda · Horario: lunes a sábado, 9:00 a.m. a 8:00 p.m., Zulia', 10.1985, -71.3143, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Acopio Cabimas - Punto 1 (frente Hotel Costa Sol)', 'Carretera H, frente al Hotel Costa Sol (antiguo El Remanso), Cabimas, Zulia', 10.395, -71.445, NULL, NULL, NULL, 'alcaldiabcabimas_', NULL, NULL),
  ('Acopio Cabimas - Punto 2 (frente Corpoelec)', 'Avenida 32 con Carretera H, frente a las oficinas de Corpoelec, Cabimas, Zulia', 10.39, -71.447, NULL, NULL, NULL, 'alcaldiabcabimas_', NULL, NULL),
  ('Acopio Cabimas - Punto 3 (CC Borjas, Xtrema 98.9FM)', 'Carretera H, Centro Comercial Borjas, estación radial Xtrema 98.9FM, Cabimas, Zulia', 10.385, -71.449, NULL, NULL, NULL, 'alcaldiabcabimas_', NULL, NULL),
  ('Colegio de Médicos del Zulia', 'Av. 16 con Calle 56, Maracaibo 4005, Zulia', 10.665, -71.62, NULL, NULL, NULL, 'comezu_2021', NULL, NULL),
  ('"Korea Japón Motor"', 'Av. 15 Delicias con Calle 69, pasando la Clínica de Izot, Maracaibo, Zulia', 10.648, -71.623, NULL, NULL, NULL, NULL, NULL, NULL),
  ('"Pandaventura" CC Galerías', 'CC Galerías Mall, planta baja, frente al Restaurante Oasis, Maracaibo, Zulia', 10.674, -71.608, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Alcaldía de Maracaibo — Centro Deportivo y Cultura Patria Joven', 'Av. 92 y 94, entre calles 79G y 79H, Maracaibo, Zulia', 10.643, -71.644, NULL, '8:00am - 6:00pm', NULL, 'alcaldiabmcbo', NULL, NULL),
  ('Alcaldía de Maracaibo — Plaza Para Todos (Antigua Plaza de Toros)', 'Plaza Para Todos (Antigua Plaza de Toros), Av. 16 Guajira con prolongación Circunvalación 2, Maracaibo, Zulia', 10.639, -71.648, NULL, '8:00am - 6:00pm', NULL, 'alcaldiabmcbo', NULL, NULL),
  ('Grupo Nezco Venezuela — Maracaibo', 'Av. 12 entre 68-69, Local 69-95, Sector Tierra Negra, Maracaibo, Zulia', 10.663, -71.621, NULL, NULL, '+584246081907', NULL, NULL, NULL),
  ('U.E. Nuestra Sra. del Valle — VALLEMUN', 'Unidad Educativa Nuestra Sra. del Valle, Maracaibo, Zulia', 10.661, -71.608, NULL, 'Viernes 26 de junio, 8:00am - 5:00pm', NULL, NULL, NULL, NULL),
  ('Elio''s Bakery Shop — Kiosko Azul', 'Kiosko Azul, Zona Oeste, Valle Claro, frente a los edificios, al lado de Súper Fruty, Maracaibo, Zulia', 10.68, -71.64, NULL, 'A partir de las 4:30pm', NULL, 'eliosbakeryshop', NULL, NULL),
  ('Bakery Motion — Plaza 75', 'Plaza 75, Local 1, Calle 75 con Avenida 3H, Sector La Lago, Maracaibo, Zulia', 10.668, -71.623, NULL, NULL, NULL, 'bakerymotion', NULL, NULL),
  ('BioSouthTech / UNIMED — Clínica Centro Médico Docente Paraíso', 'Clínica Centro Médico Docente Paraíso — Piso 1 (Unidad de Investigación Dr. "Shubert Camacho" UNIMED) y Planta Baja (Unidad de Anatomía Patológica, Dra. Iría Lozano), Maracaibo, Zulia', 10.67, -71.616, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Cruz Roja Venezolana — Filial Maracaibo', 'Sede de la Cruz Roja Venezolana Filial Maracaibo, Av. 11 con esquina Calle 83, Sector Veritas, Maracaibo, Zulia', 10.665, -71.615, NULL, 'A partir de las 7:00am', NULL, 'cruzrojamaracaibo', NULL, NULL),
  ('Facultad de Medicina LUZ — Plaza Paul Moreno Camacho', 'Plaza Paul Moreno Camacho, Facultad de Medicina, Universidad del Zulia, Maracaibo · Horario: viernes 26 de junio, 8:00 a.m. a 6:00 p.m., Zulia', 10.661, -71.63, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Synergy — CC Doral Center Mall', 'Synergy, CC Doral Center Mall, Maracaibo, Zulia', 10.692, -71.625, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Synergy — Mall Paseo San Francisco', 'Synergy, Mall Paseo San Francisco, San Francisco (zona metropolitana de Maracaibo), Zulia', 10.61, -71.66, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Sede Regional de Un Nuevo Tiempo (UNT Zulia)', 'Avenida 3F con Avenida Universidad, Zulia', 10.6545, -71.6402, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Pitts Bowling', 'CC Costa Verde, Av. Bella Vista, Maracaibo 4002, Zulia', 10.672, -71.62, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Proyecto Mujeres × Studio Velu — Gym Lago Club', 'Gym Lago Club, Hotel Tibisay, Av. El Milagro, Maracaibo, Zulia', 10.677, -71.601, NULL, NULL, NULL, 'proyectomujeres', NULL, NULL),
  ('Coremotif Functional Training Center', 'Coremotif Functional Training Center, Maracaibo · Dirección por DM @coremotif_vzla, Zulia', 10.674, -71.62, NULL, NULL, NULL, 'coremotif_vzla', NULL, NULL),
  ('CEVAZ — Sede Las Mercedes', 'Centro Venezolano Americano del Zulia (CEVAZ), Sede Las Mercedes, Maracaibo · Horario: lunes a viernes 8:00 a.m. a 5:00 p.m. · Sábados 8:00 a.m. a 4:00 p.m. · Domingos 8:00 a.m. a 2:00 p.m., Zulia', 10.68, -71.608, NULL, NULL, NULL, 'cevaz_zulia', NULL, NULL),
  ('CEVAZ — Sede La Limpia', 'Centro Venezolano Americano del Zulia (CEVAZ), Sede La Limpia, Maracaibo · Horario: lunes a viernes 8:00 a.m. a 5:00 p.m. · Sábados 8:00 a.m. a 4:00 p.m. · Domingos 8:00 a.m. a 2:00 p.m., Zulia', 10.7, -71.63, NULL, NULL, NULL, 'cevaz_zulia', NULL, NULL),
  ('Sambil Maracaibo — Lobby Goajira', 'Sambil Maracaibo, Lobby Goajira, Av. 17 Los Haticos, Maracaibo · Horario: desde las 6:00 a.m., Zulia', 10.628, -71.631, NULL, NULL, NULL, 'tusambilmcbo', NULL, NULL),
  ('Centro de Arte de Maracaibo Lía Bermúdez (CAMLB)', 'Sede del CAMLB, frente al Terminal Lacustre, Plaza Baralt, Maracaibo · Horario: todos los días, 9:00 a.m. a 5:00 p.m., Zulia', 10.636, -71.612, NULL, NULL, NULL, 'camliabermudez', NULL, NULL),
  ('Arena Panter — CC Costa Verde', 'Arena Panter, CC Costa Verde, Av. Bella Vista, Maracaibo · Horario: 2:00 p.m. a 10:00 p.m., Zulia', 10.672, -71.62, '+584146718920', NULL, NULL, 'arenapanter', NULL, NULL),
  ('Parroquia San Antonio María Claret', 'Calle 78 Dr. Portillo con Av. 3E, Zulia', 10.6727, -71.616, NULL, '8:00am - 4:00pm', NULL, NULL, NULL, NULL),
  ('Fresconi Fresh Market', 'Av. 4 Bella Vista con calle 74 (antiguo Fresconi), Maracaibo, Zulia', 10.663, -71.619, NULL, 'Jueves, viernes y sábado, 8:00am - 7:00pm', '+584246514415', NULL, NULL, NULL),
  ('Hogar Clínica San Rafael', 'Calle 64 con Av. 3F, Sector Las Mercedes, Zulia', 10.666, -71.619, NULL, '8:00am - 4:00pm', NULL, NULL, NULL, NULL),
  ('Ludus Box', 'Barrio Paraíso, Calle 80 entre Av. 19 y 19A, Maracaibo 4002, Zulia', 10.663, -71.609, NULL, 'Jueves hasta 8:00pm · Viernes 6:00am - 8:00pm · Sábado 6:00am - 12:00m', NULL, 'ludusbox', NULL, NULL),
  ('Imagolab C.A. (Centro de Imágenes)', 'Calle 76 entre Av. 3H y 3Y, Edificio Villa Ota II, tercer piso, Zulia', 10.6695, -71.617, NULL, 'Lunes a viernes, 8:30am - 6:00pm', '+584146339894', 'imagolab.ve', NULL, NULL),
  ('Protección Civil Maracaibo', 'Av. 15 Delicias con Av. 16 Los Haticos, al lado de Terminal Terrestre Maracaibo, Zulia', 10.63, -71.65, NULL, NULL, '+584141479763', NULL, NULL, NULL),
  ('CAFI', 'Galpón 1, Residencias Santa Lucía, Av. El Milagro, Zulia', 10.69, -71.628, NULL, 'A partir del 26/06, 10:00am', NULL, NULL, NULL, NULL),
  ('Alfred''s Coffee Bar', 'Av 5 de Julio con Av Bella Vista, Zulia', 10.6656, -71.608, NULL, NULL, NULL, 'alfredscoffeebar', NULL, NULL),
  ('Basilica de la Chinita', 'Av. 12 con calle 96, final Paseo Ciencias, Maracaibo, Zulia, Zulia', 10.6423, -71.6144, NULL, NULL, NULL, 'basilicachinita', NULL, NULL),
  ('Complejo Educativo Profesor Adelis Fusil', 'Complejo Deportivo Niños Cantores, Av. 55 con Calle 96D, Maracaibo · Horario: sábado desde las 8:00 a.m., Zulia', 10.645, -71.628, NULL, NULL, NULL, 'rayoescuela', NULL, NULL),
  ('La Casona — Sector Lanamericano', 'Av. 86, Sector Lanamericano, Maracaibo · Horario: lunes a sábado, 9:00 a.m. a 8:00 p.m., Zulia', 10.692, -71.671, '+584122503053', NULL, NULL, NULL, NULL, NULL),
  ('Iglesia María Inmaculada', 'Av. 15G con calle 50, Urb. La California, Maracaibo · Horario: martes a viernes, 4:30 p.m. a 5:30 p.m., Zulia', 10.668, -71.626, NULL, NULL, NULL, 'lainmaculadamcbo', NULL, NULL),
  ('Iglesia Tiempos de Reino', 'Frente al Estadio Luis Aparicio, al lado del galpón de Gramoca, Maracaibo · Horario: 9:00 a.m. a 12:00 a.m., Zulia', 10.665, -71.65, NULL, NULL, NULL, 'Tiemposdereinomcbo', NULL, NULL),
  ('Iglesia San Miguel Arcángel', 'Parroquia San Miguel Arcángel, Calle 100 Sabaneta, frente a la Clínica Zulia, Maracaibo · Horario: 8:00 a.m. a 7:00 p.m., Zulia', 10.633, -71.64, NULL, NULL, NULL, 'caritas.sanmiguelarcangel', NULL, NULL),
  ('Papeleras Ramírez', 'Av. 28 La Limpia, Sector Los Postes Negros, Maracaibo · Horario: lunes a sábado, 8:00 a.m. a 6:00 p.m., Zulia', 10.69, -71.63, '+584246724572', NULL, NULL, 'papelerasramirez', NULL, NULL),
  ('Farmacias YA! — Av. Universidad', 'Av. 12 con calle 61, Local 61-17, diagonal a la Clínica Paraíso, Maracaibo · Horario: lunes a domingo, 7:00 a.m. a 10:00 p.m., Zulia', 10.668, -71.609, '+584242928535', NULL, NULL, 'farmaciasya', NULL, NULL),
  ('Farmacias YA! — Millennium', 'Av. Fuerzas Armadas con calle 20, diagonal al Hospital Adolfo Pons (entre Fasto y Fresh Market), Maracaibo · Horario: lunes a domingo, 7:00 a.m. a 10:00 p.m., Zulia', 10.654, -71.64, '+584146720743', NULL, NULL, 'farmaciasya', NULL, NULL),
  ('Escuela de Futsal TECNOPAGOS F.S.', 'Sector Los Estanques, Av. 51, detrás del Hotel Maruma, Maracaibo · Horario: sábado y domingo, 9:00 a.m. a 3:00 p.m., Zulia', 10.606, -71.6516, NULL, NULL, NULL, 'somostecnopagosfs', NULL, NULL),
  ('Parroquia Nuestra Señora del Perpetuo Socorro', 'Av. 9B con calle 74, Sector Tierra Negra, Maracaibo · Horario: 9:00 a.m. a 7:00 p.m., Zulia', 10.679, -71.617, NULL, NULL, NULL, 'pperpetuosocorro.oficial', NULL, NULL),
  ('Fundación PALUZ', 'Calle 69 con Av. Bella Vista y Santa Rita, Maracaibo · Horario: desde 9:00 a.m., Zulia', 10.672, -71.611, NULL, NULL, NULL, 'somospaluz', NULL, NULL),
  ('Alcaldía de San Francisco — Centro de Acopio', 'San Francisco, estado Zulia, Zulia', 10.5739, -71.6486, '+584226437205', NULL, NULL, 'alcaldiabsanfco', NULL, 'desarrollosocialsf2407@gmail.com'),
  ('Luxor Graphic', 'Luxor Graphic, San Francisco, sector La Coromoto, calle 165, frente al Gimnasio Atlas, estado Zulia, Zulia', 10.571, -71.647, '+584246622634', NULL, NULL, NULL, NULL, NULL),
  ('CEVAZ — Sede San Francisco', 'Centro Venezolano Americano del Zulia (CEVAZ), Sede San Francisco, estado Zulia · Horario: lunes a viernes 8:00 a.m. a 5:00 p.m. · Sábados 8:00 a.m. a 4:00 p.m. · Domingos 8:00 a.m. a 2:00 p.m., Zulia', 10.575, -71.65, NULL, NULL, NULL, 'cevaz_zulia', NULL, NULL),
  ('Sede Vente San Francisco', 'Avenida 10 entre Calles 15 y 16A, Sierra Maestra, San Francisco · Horario: miércoles a domingo, 7:00 a.m. a 7:00 p.m., Zulia', 10.584, -71.6405, NULL, NULL, NULL, 'sanfrancisco_conmariacorina', NULL, NULL),
  ('Colegio Javier', 'Sierra Maestra, Calle 8, San Francisco, Zulia · Horario: sábado 27 de junio, 7:00 a.m. a 4:00 p.m., Zulia', 10.575, -71.64, '+584264555828', NULL, NULL, 'u.e.colegiojavier', NULL, NULL),
  ('Club UGAVI', 'Casco central, Villa del Rosario, Zulia · Horario: sábado, 8:00 a.m. a 8:00 p.m., Zulia', 10.327, -72.282, NULL, NULL, NULL, 'ugavired', NULL, NULL),
  ('Alcaldía de Barranquilla — Centro de Acopio', 'Cra 43 #6-120, Barranquillita, Barranquilla, Colombia', 10.985, -74.805, NULL, 'Lunes a domingo, 8:00am - 4:00pm', NULL, NULL, NULL, NULL),
  ('Calidex - Barranquilla', 'Calle 79 #42F-93, Local 102, Garden Plaza, Barranquilla, Colombia', 11.003, -74.805, NULL, NULL, NULL, NULL, 'https://calidex.co/', NULL),
  ('Tigresas de la Patria — Barranquilla', 'Calle 75 #55-50, Barranquilla · Contactos: Ana Lucía Pineda, María Tulena, Colombia', 10.99, -74.8, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Calidex - Bello (Niquía)', 'Diagonal 55 #37-41, CC Estación Niquía, Local 147, Bello, Colombia', 6.338, -75.555, NULL, NULL, NULL, NULL, 'https://calidex.co/', NULL),
  ('Dumbos Restaurante - Bello', 'Diagonal 59 #32-45, barrio Hermosa Provincia, cerca al CC Puerta del Norte, Bello, Antioquia, Colombia', 6.3375, -75.5545, '+573504500039', NULL, NULL, NULL, NULL, NULL),
  ('Calidex - Bogotá Cedritos', 'Cra 19 #147-30, Local 09, CC La Juguetería, Cedritos, Bogotá, Colombia', 4.729, -74.033, NULL, NULL, NULL, NULL, 'https://calidex.co/', NULL),
  ('Calidex - Bogotá Engativá', 'Calle 72 #82-60, Local 13 (Piso 1), Centro Empresarial Punto 72, Engativá, Bogotá, Colombia', 4.69, -74.115, NULL, NULL, NULL, NULL, 'https://calidex.co/', NULL),
  ('Calidex - Bogotá San Victorino', 'Calle 12B #9-40, CC Neos, Nivel 0, Local 010, San Victorino, Bogotá, Colombia', 4.603, -74.084, NULL, NULL, NULL, NULL, 'https://calidex.co/', NULL),
  ('Fundación Juntos Se Puede', 'Calle 104 #54 -31 Barrio Pasadena localidad Suba, Colombia', 4.74, -74.083, NULL, NULL, NULL, 'funjuntossepuede', NULL, NULL),
  ('Panggola - Bogotá San Felipe', 'Calle 76 #23-18, Barrio San Felipe, Bogotá, Colombia', 4.666, -74.0555, NULL, NULL, NULL, NULL, NULL, NULL),
  ('CC Tunal Sur — Puerta 06', 'DG 48b sur 24-86, CC Tunal Sur, Puerta 06, Bogotá · Horario: desde 9:00 a.m., Colombia', 4.566, -74.131, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Todos con VZLA - Bucaramanga', 'Calle 18 #21-52, Barrio San Francisco, diagonal a la Iglesia San Francisco, Bucaramanga, Santander · Horario: 7am-7pm, Colombia', 7.121, -73.119, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Calidex - Cali Norte', 'Carrera 5 #60-30, Cali Norte, Colombia', 3.472, -76.505, NULL, NULL, NULL, NULL, 'https://calidex.co/', NULL),
  ('Calidex - Cali Sur', 'Carrera 1 #61A-30, Local 10, CC Colón Plaza, Cali Sur, Colombia', 3.43, -76.535, NULL, NULL, NULL, NULL, 'https://calidex.co/', NULL),
  ('Todos con VZLA - Cali', 'Carrera 28 B3 #72S-32, Comuneros II (cerca Troncal Unida), Cali · Horario: 8am-12pm y 5pm-7pm, Colombia', 3.4, -76.515, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Tigresas de la Patria — Ferretería Tuercas y Tornillos (Cali)', 'Carrera 1 #31-134, Barrio Santander, Cali, Valle del Cauca · Contacto: Alexandra Vásquez, Colombia', 3.45, -76.532, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Comuneros II — Cl. 72q', 'Cl. 72q #28-18, Comuneros II, Cali, Valle del Cauca · Horario: 8:00 a.m. a 8:00 p.m., Colombia', 3.471, -76.479, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Centro Intégrate (Cartagena)', 'Centro Intégrate, Barrio Líbano, Cra. 49 #31B-125, detrás de Unitecnar, Cartagena, Colombia', 10.409, -75.4985, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Tigresas de la Patria — Taller de Arte Antonella Farah (Cartagena)', 'Cra 6 #4-109, Bocagrande, frente al Campito, primer piso, Cartagena · Contactos: Antonella Farah, Carolina Ariza, Colombia', 10.403, -75.552, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Comando Con Vzla — Cúcuta', 'Calle 11 A 7MA, Centro Comercial Gran Sam, segundo piso, local 243 GS, Colombia', 7.892, -72.504, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Calidex - Cúcuta', 'Avenida 6 #7N-109, Zona Industrial, Edificio Red Rubicam S.A.S., Cúcuta, Colombia', 7.91, -72.49, NULL, NULL, NULL, NULL, 'https://calidex.co/', NULL),
  ('Tigresas de la Patria — Ciudadela del Calzado (Cúcuta)', 'Av 5 #16N-108, Zona Industrial Ciudadela del Calzado, Cúcuta · Contacto: Lorena Larrota, Colombia', 7.91, -72.5, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Calidex - Medellín Centro', 'Carrera 51 #51-47, Estación Parque Berrío, CC Veracruz, Piso 3, Locales 3197-3199, Medellín, Colombia', 6.2518, -75.568, NULL, NULL, NULL, NULL, 'https://calidex.co/', NULL),
  ('Calidex - Medellín Poblado', 'Cra 35A #15B-35, Las Palmas, Centro de Negocios Prisma, Oficina 101, El Poblado, Medellín, Colombia', 6.209, -75.566, NULL, NULL, NULL, NULL, 'https://calidex.co/', NULL),
  ('Institución Educativa Héctor Abad Gómez — Placita de Flores', 'Institución Educativa Héctor Abad Gómez, sede Placita de Flores, Barrio Boston, Medellín, Colombia', 6.241, -75.561, NULL, '8:00am - 5:00pm', NULL, NULL, NULL, NULL),
  ('ENVIAR Courier - Medellín (Belén)', 'Diagonal 74B calle 32-10, sobre la Av. Bolivariana, a una cuadra del Parque de Belén, Medellín · Horario: L-V 8am-5pm, Sáb 8am-1pm, Colombia', 6.233, -75.598, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Arroz Caracas - Medellín', 'Carrera 84 #33-52, Barrio Laureles La Castellana, cerca de la universidad adventista, Medellín · Horario: Mar-Dom 12-7pm, Colombia', 6.243, -75.6, '+573504500039', NULL, NULL, NULL, NULL, NULL),
  ('Parrillas Caracas - Medellín', 'Carrera 78 #45a-04, Barrio Velódromo, Medellín · Horario: Mar-Jue 4-10pm, Vie-Sáb 2-11pm, Dom 12-9pm, Colombia', 6.248, -75.587, '+573504500039', NULL, NULL, NULL, NULL, NULL),
  ('Tepuy Laureles', 'Carrera 73 C3-5, Colombia', 6.2428, -75.5962, NULL, NULL, NULL, 'tepuysv', NULL, NULL),
  ('Tigresas de la Patria — Central Mayorista de Antioquia', 'Central Mayorista de Antioquia, Bloque 21, Local 6, Medellín · Contacto: Eliana López, Colombia', 6.228, -75.566, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Todos con VZLA - Montería', 'Calle 28A #4W-79, Barrio San Miguel, Margen Izquierda, Montería, Córdoba · Horario: 7am-7pm, Colombia', 8.746, -75.895, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Tigresas de la Patria — Montería', 'Calle 69 #3-86, Barrio El Recreo, Montería · Contacto: María Victoria Pineda, Colombia', 8.747, -75.881, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Todos con VZLA - Santa Marta', 'Parque La Tenería, Carrera 2 con 1D-36, cerca de Playa Los Cocos, Santa Marta · Horario: 7am-6pm, Colombia', 11.241, -74.205, NULL, NULL, NULL, NULL, NULL, NULL),
  ('El Refugio del Bolso - Envigado', 'Calle 39 sur #40-74, Envigado, diagonal a la Cámara de Comercio, Colombia', 6.169, -75.588, '+573504500039', NULL, NULL, NULL, NULL, NULL),
  ('Tepuy Envigado, Colombia', 'Tv. 32a Sur #31e - 20, Zona sur, Envigado, Antioquia, Colombia, Colombia', 6.166, -75.5821, NULL, NULL, NULL, 'tepuysv', NULL, NULL),
  ('Fundación Carks - Rionegro (La Provincia)', 'Sector La Provincia, Rionegro, Antioquia (contacto: Gabriela Izarra) · fundacioncarks.com, Colombia', 6.15, -75.38, '+573504500039', NULL, NULL, NULL, NULL, NULL),
  ('CC Banco Ganadero', 'CL 49 CR 50-59, CC Banco Ganadero, Local 211, Rionegro, Antioquia · Horario: 9:00 a.m. a 6:00 p.m., Colombia', 6.153, -75.376, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Tigresas de la Patria — Froylan Café (Putumayo)', 'Calle 9 #6-14, Centro Comercial Río Plaza, Local 109, Froylan Café, Mocoa, Putumayo · Contacto: Carolina Ordóñez Imbachi, Colombia', 1.15, -76.65, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Tigresas de la Patria — Florencia (Caquetá)', 'Cra 10 A #7-08, Barrio Avenidas, Florencia, Caquetá · Contacto: Marisol Arciniegas, Colombia', 1.614, -75.606, NULL, NULL, NULL, NULL, NULL, NULL),
  ('La Alborada', 'La Alborada, Cra 26A 4B-115, Manzana M, Casa 42, Villavicencio · Horario: 9:00 a.m. a 7:00 p.m., Colombia', 4.142, -73.626, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Ayuda Humanitaria Venezuela — Depósito Principal', 'Value Store It, 5900 NW 102nd Ave, #1007, Doral, FL 33178, Estados Unidos', 25.82, -80.355, NULL, NULL, NULL, 'ayudahumanitariavzla', 'https://www.ayudahumanitariavenezuela.org/centrosdeacopio/', NULL),
  ('Community Center — Doral Legacy Park', '11400 NW 82nd Street, Doral, FL 33178, Estados Unidos', 25.821, -80.328, NULL, 'Lunes a viernes 5:00pm - 9:00pm · Fines de semana 8:00am - 5:00pm', NULL, NULL, NULL, NULL),
  ('Global Empowerment Mission (GEM) — Sede Calle 14', '10815 NW Calle 14, Doral, FL, Estados Unidos', 25.789, -80.353, NULL, 'Lunes a viernes, 9:00am - 4:00pm', NULL, NULL, NULL, NULL),
  ('Oficina de la Supervisora de Elecciones de Miami-Dade', '2700 NW 87th Ave, Doral, FL 33172, Estados Unidos', 25.785, -80.336, NULL, 'Lunes a viernes, 8:00am - 5:00pm', NULL, NULL, NULL, NULL),
  ('Restaurante El Arepazo', '10191 NW 58th St, Doral, FL 33178, Estados Unidos', 25.821, -80.353, NULL, '24 horas, lunes a domingo', NULL, NULL, NULL, NULL),
  ('Caracas Bakery', '7884 NW 52nd St, Estados Unidos', 25.8195, -80.3553, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Global Empowerment Mission', '1850 NW 84th Ave #100, Doral, FL 33126, Estados Unidos', 25.817693, -80.352936, NULL, NULL, '(800) 995-7604', NULL, NULL, NULL),
  ('La Uchireña — Doral', 'La Uchireña, 7878 NW 52nd St, Doral, FL 33166 · Horario: domingo 28, 10:00 a.m. a 1:00 p.m., Estados Unidos', 25.821, -80.317, NULL, NULL, NULL, NULL, NULL, NULL),
  ('All for Vzla', '1391 NW 187 Ave, Pembroke Pines, Estados Unidos', 26.0123, -80.3382, NULL, NULL, NULL, 'https://www.instagram.com/p/DZ_cLtxuR0O/?igsh=MWdkcHdqZXVvYW96Zg==', NULL, NULL),
  ('Comando Con Vzla — San Antonio Texas', '16111 San Pedro Ave, San Antonio, TX 78232, Estados Unidos', 29.578, -98.497, NULL, 'A partir de la 1:00pm', NULL, NULL, NULL, NULL),
  ('16111 San Pedro Ave', '16111 San Pedro Ave, San Antonio, TX 78232 · Horario: desde 11:00 a.m., Estados Unidos', 29.578, -98.47, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Friends of the Children Venezuela — Brickell', '1333 S Miami Ave, Suite 101, Brickell, Miami, Estados Unidos', 25.766, -80.194, NULL, NULL, NULL, NULL, NULL, NULL),
  ('South Cargo', '6708 NW 82 Ave, Miami, Estados Unidos', 25.82, -80.32, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Organización AFE', '6090 NW 84th Ave, Miami, FL 33166, Estados Unidos', 25.812, -80.318, NULL, '9:30am - 3:00pm', '+13056024466', NULL, NULL, NULL),
  ('Caracas Bakery', '7283 Biscayne Blvd, Estados Unidos', 25.823, -80.186, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Americargo Miami', '5585 NW 72nd Ave, Miami, FL 33195 · Horario: sábados únicamente, 9:00 a.m. a 1:00 p.m., Estados Unidos', 25.821, -80.311, NULL, NULL, NULL, 'americargo', 'https://americargomiami.com', NULL),
  ('Miami Team Store — Nu Stadium', 'Nu Stadium, 1000 Stadium Drive, Miami, FL · Horario: 26 jun – 3 jul, 9:00 a.m. a 3:00 p.m. · Domingo 28 jun horario especial 6:00 p.m. a 8:30 p.m. (concierto Carín León), Estados Unidos', 25.958, -80.2389, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Bonjour Bistro — Kendall', 'Bonjour Bistro, 16650 SW 88th St, Kendall, FL · Horario: sábado 27, 10:00 a.m. a 2:00 p.m., Estados Unidos', 25.69, -80.44, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Centro de Acopio Olivera Rodríguez', '84 Hawthorns St, Chelsea, MA, Estados Unidos', 42.392, -71.033, NULL, 'Viernes, sábado y domingo · todo el día', '+18572009393', NULL, NULL, NULL),
  ('Friends of the Children Venezuela — Coral Gables', '6705 Red Road Suite 504, Coral Gables, FL, Estados Unidos', 25.724, -80.288, NULL, NULL, NULL, NULL, NULL, NULL),
  ('La Francia Joyería', '2100 Dallas Parkway Ste 150, Dallas, TX, Estados Unidos', 32.955, -96.821, NULL, '27 al 29 de junio, 2:00pm - 6:00pm', NULL, NULL, NULL, NULL),
  ('Metabox Cargo — Katy', '19308 Morton Rd #106, Katy, TX 77449, Estados Unidos', 29.786, -95.778, NULL, '9:00am - 5:00pm', NULL, NULL, NULL, NULL),
  ('Metabox Cinco Ranch — Katy', '25600 Westheimer Pkwy, Katy, TX 77494, Estados Unidos', 29.735, -95.817, NULL, '12:00pm - 8:00pm', NULL, NULL, NULL, NULL),
  ('Beat Training — Centro de Acopio', '904 E Osceola Pkwy, Kissimmee, FL 34744, Estados Unidos', 28.3203, -81.4047, NULL, 'Sábado, 9:00am - 1:00pm', NULL, 'beattrainingglobal', NULL, NULL),
  ('Arepas Santa Bárbara', 'Arepas Santa Bárbara, 1016 Buenaventura Blvd, Kissimmee, FL 34743 · Horario: 10:00 a.m. a 2:00 p.m., Estados Unidos', 28.31, -81.406, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Friends of the Children Venezuela — Key Biscayne', '792 Ridgewood Rd, Key Biscayne, FL, Estados Unidos', 25.689, -80.162, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Centro de Acopio Miami Lakes', '6135 NW 167 Suite E13, Miami Lakes, FL, Estados Unidos', 25.916, -80.311, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Budare Café — Queens', '9406 Roosevelt Avenue, Queens, NY, Estados Unidos', 40.747, -73.874, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Casa Ora — Brooklyn', '148 Meserole St, Brooklyn, NY, Estados Unidos', 40.716, -73.943, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Lullas — Brooklyn', '169 Graham Avenue, Brooklyn, NY, Estados Unidos', 40.71, -73.944, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Classic Arepas (@classicarepas)', '31 W 8th St, New York, NY 10011, Estados Unidos', 40.733, -73.998, NULL, NULL, NULL, 'classicarepas', NULL, NULL),
  ('KOË', '601 W Taft Vineland Rd, Orlando, FL 32824 · Horario: 2:00 p.m. a 8:30 p.m., Estados Unidos', 28.409, -81.448, NULL, NULL, NULL, 'koe.usa', NULL, NULL),
  ('13256 Village Park', '13256 Village Park #200, Orlando, FL · Horario: 10:00 a.m. a 2:00 p.m., Estados Unidos', 28.415, -81.454, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Pecargo — Orinoco Dr.', 'Pecargo, 2100 Orinoco Dr., Suite 164, Orlando, FL 32837 · Horario: 10:00 a.m. a 2:00 p.m., Estados Unidos', 28.395, -81.408, NULL, NULL, NULL, NULL, NULL, NULL),
  ('10924 S Trail Circle', '10924 S Trail Circle, Orlando, FL 32837 · Horario: 10:00 a.m. a 2:00 p.m., Estados Unidos', 28.385, -81.42, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Metabox Cargo — Spring', '25115 Gosling Rd Ste 108, Spring, TX 77389, Estados Unidos', 30.123, -95.506, NULL, '10:00am - 5:00pm', NULL, NULL, NULL, NULL),
  ('Ayuda Humanitaria Venezuela — Dirección Postal', '1062 Lavender Circle, Weston, FL 33327, Estados Unidos', 26.105, -80.406, NULL, NULL, NULL, 'ayudahumanitariavzla', 'https://www.ayudahumanitariavenezuela.org/centrosdeacopio/', NULL),
  ('Friends of the Children Venezuela — Weston', '824 Regal Cove Rd, Weston, FL, Estados Unidos', 26.101, -80.406, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Weston Town Center', '1675 Market St, Weston, FL, Estados Unidos', 26.101, -80.397, NULL, '12:00pm - 6:00pm', NULL, NULL, NULL, NULL),
  ('Lulla Brooklyn (@lullabrooklyn)', '169 Graham Ave, Brooklyn, NY 11206, Estados Unidos', 40.7085, -73.944, NULL, NULL, NULL, 'lullabrooklyn', NULL, NULL),
  ('El Budare Café (@elbudarecafe) - 94-06', '94-06 Roosevelt Ave, Queens, NY 11372, Estados Unidos', 40.7478, -73.8767, NULL, NULL, NULL, 'elbudarecafe', NULL, NULL),
  ('El Budare Café (@elbudarecafe) - 87-21', '87-21 Roosevelt Ave, Queens, NY 11372, Estados Unidos', 40.749, -73.8845, NULL, NULL, NULL, 'elbudarecafe', NULL, NULL),
  ('Dulce Tropical', '2301 NE 16th St, Unit 102, Pompano Beach, FL 33062, Estados Unidos', 26.24, -80.095, NULL, NULL, NULL, 'dulcetropicalmiami', NULL, NULL),
  ('Gusticos Bistro', 'Gusticos Bistro, 2249 W Hillsboro Blvd, Deerfield Beach, FL 33442 · Horario: sábado 27, 10:00 a.m. a 2:00 p.m., Estados Unidos', 26.325, -80.173, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Bonjour Bistro — Pembroke Pines', 'Bonjour Bistro, 10800 Pines Blvd, Pembroke Pines, FL 33026 · Horario: sábado 27, 10:00 a.m. a 2:00 p.m., Estados Unidos', 26.008, -80.298, NULL, NULL, NULL, NULL, NULL, NULL),
  ('5045 W First Ave', '5045 W First Ave, Denver, CO 80219 · Horario: 11:00 a.m. a 3:00 p.m., Estados Unidos', 39.718, -105.049, NULL, NULL, NULL, NULL, NULL, NULL),
  ('9044 Lawyers Rd C', '9044 Lawyers Rd C, Mint Hill, NC 28227 · Horario: martes a sábado, 10:00 a.m. a 6:00 p.m., Estados Unidos', 35.18, -80.648, NULL, NULL, NULL, NULL, NULL, NULL),
  ('La Mora', '2004 Mason Rd, Ste D4, Katy, TX 77450 · Horario: lunes a domingo, 10:00 a.m. a 9:00 p.m., Estados Unidos', 29.786, -95.747, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Metabox Cargo — Katy', '19308 Morton Rd, Suite #106, Katy, TX 77449 · Horario: lunes a sábado, 9:00 a.m. a 5:00 p.m., Estados Unidos', 29.819, -95.734, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Metabox Cargo — Cinco Ranch (Mi Querencia)', '25600 Westheimer Pkwy, Katy, TX 77494 · Horario: lunes a domingo, 12:00 p.m. a 6:00 p.m., Estados Unidos', 29.735, -95.796, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Mi Pueblito Restaurante', '20940 Katy Fwy, Katy, TX · Horario: lunes a sábado, 10:00 a.m. a 10:00 p.m., Estados Unidos', 29.786, -95.728, NULL, NULL, NULL, NULL, NULL, NULL),
  ('El Kourmet', '25757 Westheimer Pkwy, Katy, TX · Horario: lunes a domingo, 8:00 a.m. a 10:00 p.m., Estados Unidos', 29.735, -95.798, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Leobel Martínez Group', '24329 Kingsland Blvd #400, Katy, TX 77494 · Horario: lunes a domingo, 9:00 a.m. a 7:00 p.m., Estados Unidos', 29.78, -95.782, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Dukes Katy', '1420 S Mason Rd, Suite 110, Katy, TX 77450 · Horario: lunes a domingo, 8:00 a.m. a 8:00 p.m., Estados Unidos', 29.778, -95.747, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Uptown Barber Zone', '829 S Mason Rd #255, Katy, TX 77450 · Horario: lunes a domingo, 9:00 a.m. a 8:00 p.m., Estados Unidos', 29.782, -95.747, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Ángel Family Clinic', '5330 Fry Rd, Ste C, Katy, TX 77449 · Horario: lunes a sábado, 8:30 a.m. a 4:00 p.m., Estados Unidos', 29.821, -95.734, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Pa'' Que La Negra', '6182 Highview Dr #A, Houston, TX 77084 · Horario: lunes a domingo, 6:00 p.m. a 11:30 p.m., Estados Unidos', 29.818, -95.65, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Acción Social — Venezuela', '12180 West Houston Center Blvd, Houston, TX 77077 · Horario: a partir del lunes, todos los días en 2 horarios: 9:00 a.m. a 1:00 p.m. y 1:00 p.m. a 5:00 p.m., Estados Unidos', 29.761, -95.621, NULL, NULL, NULL, NULL, NULL, NULL),
  ('American Help Center — Galleria Financial Center', '5065 Westheimer Rd, Suite 880, Galleria Financial Center, Houston, TX · Horario: lunes a viernes, 9:00 a.m. a 4:00 p.m., Estados Unidos', 29.74, -95.464, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Clínica Integral San Juan Diego', '12168 Bellaire Blvd, Ste 178, Houston, TX · Horario: lunes a sábado, 9:00 a.m. a 6:00 p.m., Estados Unidos', 29.674, -95.61, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Esmafitness Memorial', '1322 S Dairy Ashford Rd, Houston, TX 77077 · Horario: lunes a viernes, 7:00 a.m. a 7:00 p.m., Estados Unidos', 29.74, -95.619, NULL, NULL, NULL, NULL, NULL, NULL),
  ('QSTT Logistics', '15945 Morales Rd, Bldg. C, Ste. 200, Houston, TX · Horario: lunes a viernes, 9:00 a.m. a 5:00 p.m., Estados Unidos', 29.76, -95.65, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Principrin School', '2931 W 12th Street, Houston, TX 77008 · Horario: lunes a viernes, 7:00 a.m. a 6:00 p.m., Estados Unidos', 29.799, -95.428, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Advanced Rehabilitation Clinics of Texas', '2600 South Gessner Rd, Ste 111, Houston, TX 77063 · Horario: lunes a viernes, 9:00 a.m. a 6:00 p.m., Estados Unidos', 29.737, -95.552, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Pa'' Que Maru', '4410 42nd St, Dickinson, TX 77639 · Horario: lunes a domingo, 9:00 a.m. a 5:00 p.m., Estados Unidos', 29.46, -95.051, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Metabox Cargo — Spring', '25115 Gosling Rd, Suite 108, Spring, TX 77389 · Horario: lunes a domingo, 12:00 p.m. a 6:00 p.m., Estados Unidos', 30.1, -95.47, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Porter Tax Multiservices', '22323 SH-494 Loop, Unit 1A, Kingwood, TX · Horario: lunes a jueves, 10:00 a.m. a 3:00 p.m., Estados Unidos', 30.047, -95.227, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Jump and Play', '27620 TX-249, Ste A6, Tomball, TX 77375 · Horario: lunes a sábado, 9:00 a.m. a 8:00 p.m. · Domingo 9:00 a.m. a 7:00 p.m., Estados Unidos', 30.089, -95.644, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Rua Formosa 297', 'Rua Formosa 297, 2.º frente, 4000-252 Porto · Horário: Segunda a sábado, 11:00 às 17:00, Portugal', 41.149, -8.609, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Restaurante Destino', 'Restaurante Destino, R. de Serpa Pinto 644, Porto · Horário: Segunda a sexta, 8:00 às 22:00, Portugal', 41.162, -8.624, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Rua Dr. Mário Sacramento', 'Rua Dr. Mário Sacramento, 3810-105 Aveiro · Horário: Terça a domingo, 10:00 às 21:00, Portugal', 40.641, -8.653, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Praça do Colombo', 'Praça do Colombo, 90000-057 Funchal, Madeira · Horário: 16:30 às 17:00, Portugal', 32.65, -16.909, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Calçada da Tapada 15', 'Calçada da Tapada 15, 1300-544 Lisboa · Horário: 11:00 às 14:00, Portugal', 38.708, -9.181, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Caracas de Ayer', 'Calle Cuicuilco 8, colonia Letrán Valle, alcaldía Benito Juárez, CDMX, México', 19.37, -99.166, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Centro de Acopio Ayuda a Venezuela — Roma Sur', 'Calle Tehuantepec 36, colonia Roma Sur, alcaldía Cuauhtémoc, CDMX, México', 19.403, -99.162, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Brigada de Rescate Topos Tlaltelolco', 'Magistrados 75, Amp. El Sifón, Iztapalapa, 09180 Ciudad de México, CDMX, México', 19.354, -99.086, NULL, NULL, NULL, 'topos.mx', 'https://topos.mx', NULL),
  ('Thelmas Cakes', 'Thelmas Cakes, Ciudad de México · Horario: 9:00 a.m. a 8:00 p.m., México', 19.4326, -99.1332, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Rivas Express — Narvarte', 'Local Rivas Express, Diagonal San Antonio 1115, Local E1, Col. Narvarte Poniente, Benito Juárez, C.P. 03020, CDMX · Horario: 10:00 a.m. a 6:00 p.m., México', 19.4, -99.164, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Viloria Clínica Dental — Del Valle', 'Viloria Clínica Dental, Calle Tlacoquemecatl 156, Colonia Del Valle, Benito Juárez, CDMX · Horario: 9:00 a.m. a 6:00 p.m., México', 19.385, -99.17, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Parroquia San Miguel Arcángel', 'Parroquia San Miguel Arcángel, Col. Multi80, Villahermosa · Horario: 10:00 a.m. a 6:00 p.m., México', 17.989, -92.947, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Avenida de las Américas 1241', 'Avenida de las Américas 1241, Colonia Circunvalación (Providencia), Guadalajara · Tel: 33 12 55 67 30 (Hassan, 24/7) · Horario: 9:00 a.m. a 7:00 p.m., México', 20.689, -103.387, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Viveros del Valle', 'Viveros del Valle, Zapopan, Jalisco, C.P. 45138 · Horario: 9:00 a.m. a 7:00 p.m., México', 20.712, -103.406, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Anita Ventas — Centro de Acopio', 'Domingo Aramburu 1735, Montevideo, Uruguay, Uruguay', -34.858, -56.162, NULL, 'Lunes a viernes 9:00am - 5:00pm · Sábados hasta las 2:00pm', '+59896122609', 'anitaventas.uy', NULL, NULL),
  ('BlueMall Santo Domingo — Centro de Acopio', 'BlueMall Santo Domingo, Piso -1, Oficinas Administrativas, Av. Winston Churchill, Santo Domingo, República Dominicana', 18.472, -69.942, NULL, 'Lunes a viernes 9:00am - 6:00pm · Sábado y domingo 9:00am - 12:00pm', NULL, NULL, NULL, NULL),
  ('Centro de Acopio Sambil Santo Domingo', 'Sambil Santo Domingo, Av. John F. Kennedy, Santo Domingo, República Dominicana', 18.479, -69.942, NULL, '10:00am - 7:00pm', NULL, 'tusambildo', NULL, NULL),
  ('Downtown Center — Centro de Acopio', 'Downtown Center, Sótano 2 (S2), Santo Domingo · Horario: viernes 26 jun – miércoles 1 jul, 9:00 a.m. a 4:00 p.m. · Fin de semana 10:00 a.m. a 7:00 p.m., República Dominicana', 18.467, -69.941, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Food Truck Village', 'Av. Gustavo Mejía Ricart 62-66, Santo Domingo · Horario: todos los días, 6:00 p.m. a 12:00 a.m., República Dominicana', 18.473, -69.939, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Restaurante Monte Cristo', 'Av. Gustavo Mejía Ricart 44, Santo Domingo, República Dominicana', 18.4729, -69.94, NULL, NULL, NULL, NULL, NULL, NULL),
  ('El Arepanito', 'Av. Winston Churchill 26, Santo Domingo · Horario: todos los días, 7:00 a.m. a 12:00 a.m., República Dominicana', 18.4655, -69.941, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Centro Familiar de Taekwondo — Mirador Sur', 'Sede Mirador Sur, Santo Domingo · Horario: lunes a viernes 8:00 a.m. a 7:00 p.m. · Sábado 9:00 a.m. a 4:00 p.m., República Dominicana', 18.4424, -69.954, NULL, NULL, NULL, 'centrofamiliartkd', NULL, NULL),
  ('Centro Médico Docente Siglo 21', 'Autoservicio del Centro Médico Docente Siglo 21, Calle Luperón esq. Sánchez, Santo Domingo · Horario: lunes a viernes 8:00 a.m. a 6:00 p.m. · Sábados 8:00 a.m. a 12:00 p.m., República Dominicana', 18.472, -69.905, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Katy Guillén Studio', 'Edificio Las Camelias, Av. Perú, Piso 4, Oficina 404 C, Bella Vista, Santo Domingo · Horario: lunes a sábado, 9:00 a.m. a 3:00 p.m., República Dominicana', 18.452, -69.945, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Club de Leones El Millón', 'Club de Leones El Millón, peatonal Domingo Mallol, Urb. Ciudad de los Millones, D.N. detrás de la Plaza Saint Michel, Santo Domingo · Horario: 8:00 a.m. a 8:00 p.m., República Dominicana', 18.464, -69.951, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Hard Rock Café Punta Cana', 'Downtown Punta Cana, La Altagracia · Horario: 9:00 a.m. a 9:00 p.m., República Dominicana', 18.582, -68.405, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Punto de Acopio — Alto Llano', 'Av. Barceló, Alto Llano, Punta Cana, República Dominicana', 18.578, -68.41, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Orangetheory Fitness Santiago', 'Av. 27 de Febrero con calle Erick Eckman, Santiago de los Caballeros, República Dominicana', 19.452, -70.697, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Asociación de Venezolanos — Librería Paulinas', 'Librería Paulinas, Calle 16 de Agosto, Centro Histórico, Santiago de los Caballeros, República Dominicana', 19.4517, -70.697, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Guardería Rayitos de Sol', 'Guardería Rayitos de Sol, F.A. Dorado III, Casa 9 manzana K, Jacobo Majluta, Santo Domingo Norte · Horario: desde 6:30 a.m., República Dominicana', 18.553, -69.922, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Colegio Educando a Tiempo para el Futuro', 'Colegio Educando a Tiempo para el Futuro, Sosúa, Puerto Plata · Horario: 8:00 a.m. a 8:00 p.m., República Dominicana', 19.753, -70.522, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Centro de Acopio Buenos Aires — Amenabar', 'Amenabar 1024, CABA, Buenos Aires, Argentina', -34.557, -58.4555, NULL, '13:00 - 19:00', NULL, NULL, NULL, NULL),
  ('Centro de Acopio Buenos Aires — Libertad', 'Libertad 996, CABA, Buenos Aires, Argentina', -34.5945, -58.3811, NULL, '10:00 - 21:00', NULL, NULL, NULL, NULL),
  ('Cambur Pintón — Sede', 'Calle Canadá 2080, Comodoro Rivadavia, Chubut, Argentina', -45.865, -67.49, NULL, 'Hasta el jueves 2 de julio, 13:00', '+5492975293518', 'camburpinton_cr', NULL, NULL),
  ('Shaka''s Car Wash', 'Calle José Álvarez al 95, Barrio Industrial, Comodoro Rivadavia, Chubut, Argentina', -45.863, -67.487, NULL, 'Hasta el jueves 2 de julio, 13:00', '+5492975293518', 'camburpinton_cr', NULL, NULL),
  ('Centro Médico La Viña', 'Edificio Empresarial Prima Esperanza, VIP Medical Care, Lima, Perú', -12.119, -77.029, NULL, NULL, NULL, NULL, NULL, NULL),
  ('VIP Medical Care — Sede Miraflores', 'Calle Porta 130, Piso 5, oficina 508, Miraflores, Lima, Perú', -12.128, -77.029, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Av. 28 de Julio 2491 — La Victoria', 'Av. 28 de Julio 2491, La Victoria, Lima · Horario: 7:00 a.m. a 9:00 p.m., Perú', -12.068, -77.022, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Plaza de Armas', 'Plaza de Armas, Trujillo · Horario: 8:00 a.m. a 8:00 p.m. (viernes, sábado y domingo), Perú', -8.112, -79.029, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Jr. Amazonas N124', 'Jr. Amazonas N124 (detrás del Open Plaza), Huancayo · Horario: desde 10:00 a.m., Perú', -12.07, -75.205, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Urb. 15 de Agosto — Paucarpata', 'Urbanización 15 de Agosto, Paucarpata, Arequipa · Horario: 10:00 a.m. a 7:00 p.m., Perú', -16.425, -71.507, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Comando Con Vzla — Casa Club Casa Omar', 'Casa Club Casa Omar, Ciudad de Panamá, Panamá', 8.992, -79.518, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Alcaldía de Panamá', 'Teatro Gladys Vidal, planta baja del Edificio Hatillo., Panamá', 8.9824, -79.5199, NULL, NULL, NULL, 'https://www.instagram.com/p/DaApTBKkTd7/?igsh=MWVub3c3aWR1MXhkMA%3D%3D', NULL, NULL),
  ('Comando Con Vzla — Ibarra', 'Calle García Moreno 2-58 y Maldonado, a media cuadra del Subcentro de Salud N° 1, Ecuador', 0.349, -78.122, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Cachapas El Félix', 'Av. Naciones Unidas y Av. 10 de Agosto, Quito Norte, Ecuador', -0.181, -78.487, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Edificio Gaudí', 'Calle Checoslovaquia, Quito, Ecuador', -0.183, -78.483, NULL, NULL, NULL, NULL, NULL, NULL),
  ('IMPAQTO La Carolina — Cámara de Comercio Ecuatoriano Venezolana', 'Av. Shyris y Suecia, Edificio IQON, Quito, Ecuador', -0.179, -78.483, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Restaurante Don Lucho', 'Av Rumichaca Ñan, frente al estadio, Quito · Horario: 8:00 a.m. a 5:00 p.m., Ecuador', -0.27, -78.55, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Edif. Julio Cesar — Chillogallo', 'Av Rumichaca Ñan y Calle Moromoros, Edif. Julio Cesar, Local 03, Sector Chillogallo (frente al estadio del Aucas — el sur), Quito · Horario: 9:00 a.m. a 4:00 p.m., Ecuador', -0.282, -78.556, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Udyat Fitness Club', 'Udyat Fitness Club (Piscina), Av. París N40-108 y De los Granados, Quito · Horario: 9:00 a.m. a 8:00 p.m., Ecuador', -0.175, -78.488, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Av. Napo Casa S6-308', 'Avenida Napo Casa S6-308, frente al colegio Montúfar, al lado de la peluquería Ooh!, Quito · Horario: 8:00 a.m. a 4:00 p.m., Ecuador', -0.251, -78.518, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Local Virtus — Miraflores', 'Redondel para entrar a Miraflores, calle Olmedo y Francisco Flor, pasos arriba del colegio Cevallos, Local Virtus, Quito · Horario: 9:00 a.m. a 7:00 p.m., Ecuador', -0.204, -78.492, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Edificio Portal del Sol', 'Av. 12 de Octubre y calle Emilio Carrere, sector Yanuncay, Cuenca, Ecuador', -2.91, -79.019, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Comando Con Vzla — Chamos Burger', 'Víctor Emilio Estrada y Jiguas, diagonal al Novagym Urdesa, local Chamos Burger, Guayaquil, Ecuador', -2.162, -79.908, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Sociedad Civil', 'Alborada 4ta etapa manzana FF Villa 6. Avenida José María Roura llegando al comisariato, atrás de ferrisariato, Ecuador', -2.148, -79.887, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Un Rincón de Venezuela — Alborada', 'Alborada 11va, Mz 30, Villa 28, Guayaquil — Un Rincón de Venezuela · Horario: 4:00 p.m., Ecuador', -2.138, -79.9, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Mucholote 1, 7ma etapa', 'Mucholote 1, 7ma etapa, Guayaquil · Horario: 10:00 a.m., Ecuador', -2.17, -79.89, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Casa Comunal La Comarca', 'Sector Quitumbes Ninallacta, Casa Comunal La Comarca, Quito · Horario: 24 horas, Ecuador', -0.303, -78.553, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Terminal Centro de Atención al Migrante', 'Terminal centro de atención al migrante, entrada por el patio de comida, Santo Domingo de los Tsáchilas · Horario: 9:00 a.m. a 8:00 p.m., Ecuador', -0.253, -79.175, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Municipio — Av. Quito con Tsáchila', 'Municipio, Av. Quito con calle Tsáchila al lado del Salón de la Ciudad, Santo Domingo de los Tsáchilas · Horario: 9:00 a.m. a 8:00 p.m., Ecuador', -0.254, -79.174, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Calle Manuelita Sáez — Liberación Popular', 'Calle Manuelita Sáez o Liberación Popular, con calle La Niña, frente al local de Alejandra Osorio Lashista, ref. Escuela UNE, Santo Domingo de los Tsáchilas · Horario: 9:00 a.m. a 8:00 p.m., Ecuador', -0.256, -79.177, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Parque Turismo — Valle de los Chillos', 'Parque Turismo, Valle de los Chillos, Sangolquí · Horario: desde 10:00 a.m., Ecuador', -0.332, -78.448, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Parroquia 7 de Octubre', 'Parroquia 7 de Octubre, calle 7ma y la B, Quevedo · Horario: desde las 8:00 a.m., Ecuador', -1.022, -79.464, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Tufastmarket — Redondel de la Cumandá', 'Av. 12 de Noviembre, Tufastmarket / Redondel de la Cumandá, Ambato · Horario: 8:00 a.m. a 8:00 p.m., Ecuador', -1.249, -78.616, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Mi Trámite Migratorio — Santiago Centro', 'Av. Portugal 412, Strip Center, Local 21, Santiago Centro, Chile', -33.4485, -70.6404, NULL, 'Lunes a viernes 09:00 - 18:00 · Sábado 09:00 - 14:00', NULL, NULL, NULL, NULL),
  ('Restaurante Calderos — Santiago Centro', 'San Isidro 401, Santiago Centro, Chile', -33.441, -70.6388, NULL, 'Lunes a domingo, 12:00 - 22:00', NULL, NULL, NULL, NULL),
  ('Rumbo Sur — Centro de Acopio', 'Zenteno 183, Santiago Centro, Santiago de Chile, Chile', -33.445, -70.651, NULL, NULL, NULL, 'rumbosur.cl', 'https://www.instagram.com/rumbosur.cl/', NULL),
  ('Papelón Sabroso — Centro de Acopio', 'Av. Providencia 1669, Providencia, Santiago de Chile, Chile', -33.4255, -70.6235, NULL, 'Lunes a sábado, 9:00 - 21:00 · Domingo, 9:00 - 18:00', NULL, 'visualizaudios', NULL, NULL),
  ('Centro de Acopio Santiago de Chile', 'Av. Providencia 1669, Santiago, Chile', -33.4265, -70.619, NULL, NULL, NULL, 'papelonsabroso', NULL, NULL),
  ('AACV — Asociación de Ayuda Comunitaria Venezolana', 'Calle Francisco García Talavera 2, Santa Cruz de Tenerife, España', 28.472, -16.25, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Una Vzlana en Madrid — Sambil Madrid', 'Sambil Madrid, Planta 0, Madrid, España', 40.4837, -3.668, NULL, 'Sábado y domingo, 10:00 a 18:30', NULL, 'unavzlanaenmadrid', NULL, NULL),
  ('Refugiados sin fronteras', 'Calle Matilde Landa 26, España', 40.425, -3.7, NULL, NULL, NULL, 'https://www.instagram.com/p/DaAU3uXoUdw/', NULL, NULL),
  ('Gramabar (Grama Lounge)', 'Grama Lounge / Gramabar, Madrid, España', 40.4378, -3.6795, NULL, NULL, NULL, 'gramabar', NULL, NULL),
  ('Clínica Menorca', 'Clínica Menorca, Madrid, España', 40.4258, -3.6839, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Diáspora en Movimiento', 'Calle Matilde Landa 26, Madrid, España', 40.4729, -3.6928, NULL, NULL, NULL, 'diasporaenmovimientovzla', NULL, NULL),
  ('San Blas - Estadio Metropolitano', 'Estadio Metropolitano (parking oeste), San Blas-Canillejas, Madrid · Dom 08:00-15:00, España', 40.4362, -3.5995, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Chamberí - Taquería La Lupita (Zurbano)', 'Taquería La Lupita, Zurbano 67, Chamberí, Madrid · Vie 13:00-00:00, España', 40.4365, -3.694, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Centro - Taquería La Lupita (Conde de Xiquena)', 'Taquería La Lupita, Conde de Xiquena 10, Madrid · Vie 13:00-00:00, España', 40.423, -3.694, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Chamberí - Panadería Levadura Madre', 'Panadería Levadura Madre, Bravo Murillo 60, Chamberí, Madrid · Sáb y dom desde 08:00, España', 40.4395, -3.703, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Fuencarral-El Pardo', 'Plaza de Mondariz 15, planta 12 pta 1 (Mónica Dudamel), Fuencarral, Madrid, España', 40.479, -3.708, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Ciudad Lineal', 'Emilio Ferrari 102, bajo exterior izquierdo, Ciudad Lineal, Madrid, España', 40.447, -3.648, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Carabanchel - Metro Aluche', 'Estación de Metro Aluche (cerca de taquillas/exterior), Madrid, España', 40.385, -3.756, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Salamanca - General Pardiñas', 'General Pardiñas 85, 28006, Salamanca, Madrid, España', 40.433, -3.677, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Salamanca - Núñez de Balboa', 'Núñez de Balboa 35A, 28006, Salamanca, Madrid, España', 40.428, -3.681, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Salamanca - Calle del Cid', 'Calle del Cid 2, 28001, Salamanca, Madrid, España', 40.4245, -3.684, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Salamanca - Marqués de Zafra', 'Paseo del Marqués de Zafra 7, 4D, Madrid, España', 40.429, -3.666, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Salamanca - Diego de León', 'Calle Diego de León 67, 3 izq, Salamanca, Madrid, España', 40.436, -3.672, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Tres Cantos', 'Av. 21 de Marzo 1, portal 6, 4ºB, Tres Cantos, Madrid, España', 40.602, -3.71, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Navas del Rey', 'Calle Pelayos 4B, Navas del Rey, Madrid, España', 40.356, -4.143, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Chamartín - Peluquería JJ Matamoros', 'Peluquería JJ Matamoros, Av. Alberto Alcocer 49 (Metro Colombia), SOLO RECOGIDA, hasta 22:00, Madrid, España', 40.464, -3.681, NULL, NULL, NULL, NULL, NULL, NULL),
  ('El Cañaveral (Hortaleza) - Kora Balance', 'Kora Balance, Av. de Miguel Delibes 47, El Cañaveral, Madrid · 09:30-21:30, España', 40.4, -3.57, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Algete', 'Calle Félix Rodríguez de la Fuente 23 3D, 28110, Algete, Madrid · desde 17:00, España', 40.597, -3.499, '643093680', NULL, NULL, NULL, NULL, NULL),
  ('San Sebastián de los Reyes - Bongo y Timbal', 'Bongo y Timbal, Travesía Juan Manuel Sánchez Pedagogo 2, San Sebastián de los Reyes, Madrid, España', 40.547, -3.626, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Villaverde', 'Calle Periana 28, 1-D, Villaverde, Madrid, España', 40.345, -3.69, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Leganés - Oohlala Bistró', 'Oohlala Bistró, Calle de la Rioja 134, 28915, Leganés, Madrid, España', 40.328, -3.765, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Arganzuela - Olé Dogo', 'Olé Dogo, Paseo de la Esperanza 49, 28005, Arganzuela, Madrid · Vie 08:00-20:00, Sáb 11:00-16:00, España', 40.401, -3.705, NULL, NULL, NULL, NULL, NULL, NULL),
  ('AVA Alcobendas - Parroquia Santa María de la Esperanza', 'Parroquia Santa María de la Esperanza, Alcobendas (Madrid Norte) · Sáb 27 y Dom 28 jun, 10:00-18:30, España', 40.539, -3.642, NULL, NULL, NULL, 'asoc_venezolana_alcobendas', NULL, NULL),
  ('AMS Abogados — Calle Oñate', 'Calle Oñate 10, Bajo exterior derecha, Oficina AMS Abogados, 28020 Madrid · Horario: 9:00 a.m. a 6:00 p.m., España', 40.464, -3.69, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Parroquia Santísimo Cristo de la Victoria', 'Parroquia Santísimo Cristo de la Victoria, Calle Fernando el Católico 45, Chamberí, Madrid · Horario: 8:30 a.m. a 9:00 p.m., España', 40.436, -3.718, NULL, NULL, NULL, NULL, NULL, NULL),
  ('El garaje de mamá tía', 'Calle Profesor Joaquín Hellín, La Ñora, España', 37.9894, -1.1945, '968951672', NULL, NULL, NULL, NULL, NULL),
  ('Local Tierra de Gracia', 'Local Tierra de Gracia, Plaza Moraza 4, 48007 Bilbao · Horario: 5:00 p.m. a 8:00 p.m., España', 43.264, -2.923, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Praça do Centro Cívico', 'Praça do Centro Cívico, Boa Vista · Horário: 9:00 às 19:00, Brasil', 2.82, -60.672, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Av. Nossa Sra da Consolata 2555', 'Av. Nossa Sra da Consolata 2555, Boa Vista · Horário: 9:00 às 19:00, Brasil', 2.819, -60.666, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Upa Academia Coroado 2', 'Upa Academia Coroado 2, Manaus · Horário: 6:00 às 20:00, Brasil', -3.075, -59.955, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Setor Vila Nova', 'Rua Maria Dos Anjos Pimentel Guerreiro, n102, Setor Vila Nova, Pacaraima · Horário: 9:00 às 18:00, Brasil', 4.476, -61.15, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Vengo360 — Boulevard Los Próceres', 'Vengo360, Boulevard Los Próceres 16-63, Ciudad de Guatemala · Horario: 8:00 a.m. a 4:00 p.m., Guatemala', 14.599, -90.502, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Restaurante Carne en Vara — Zona 10', 'Restaurante Carne en Vara, Zona 10, Ciudad de Guatemala · Horario: 8:00 a.m. a 4:00 p.m., Guatemala', 14.586, -90.512, NULL, NULL, NULL, NULL, NULL, NULL),
  ('SOS Therapy — todas las sedes', 'SOS Therapy (sedes CAES, Zona 14 y Zona 15), Ciudad de Guatemala · Horario: 8:00 a.m. a 4:00 p.m., Guatemala', 14.579, -90.505, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Restaurant Salvaje — Barrio Ycuá', 'Restaurant Salvaje, Esquina Calle Austria con Viena, Barrio Ycuá, Asunción · Horario: 8:00 a 22:30, Paraguay', -25.284, -57.635, NULL, NULL, NULL, NULL, NULL, NULL),
  ('N.° 1 Troche c/ Pantaleón García', 'N.° 1 Troche c/ Pantaleón García, Luque · Horario: 9:00 a 12:30 y 16:30 a 18:00, Paraguay', -25.27, -57.486, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Comité Olímpico Paraguayo', 'Comité Olímpico Paraguayo, Luque · Horario: 24 horas, Paraguay', -25.272, -57.488, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Av. Las Américas — Edif. WB Group', 'Av. Las Américas, Edificio WB Group, Área 4, Ciudad del Este · Horario: 10:00 a 21:00, Paraguay', -25.516, -54.616, NULL, NULL, NULL, NULL, NULL, NULL)
) AS v("name","address","lat","lng","phone","schedule","whatsapp","instagram","website","email")
WHERE NOT EXISTS (
  SELECT 1 FROM "public"."centers" c WHERE c."name" = v."name" AND c."address" = v."address"
);
